In [285]:
import pandas as pd
import numpy as np
# 네이버 지도의 일부 카페 리뷰를 .csv파일로 저장한 후에 불러오기
df = pd.read_csv('https://raw.githubusercontent.com/edenLee94/caffeine-meeting/main/cafe_seoul.csv')
df

,cafe_name,quary,region,evaluation,rating,coffee_price
0,umoae,합정,서교동,인테리어가 감각적이라고 느꼈습니다 사장님이 친절하시고 디저트가 맛있어요 소르베도 재...,NaN,NaN
1,umoae,합정,서교동,커피와 디저트 모두 너무 맛있어요 가게 분위기도 원목 가구를 써서 그런지 단정하고 ...,NaN,NaN
2,umoae,합정,서교동,프렌치토스트 소문대로 존맛탱,NaN,NaN
3,어반플랜트 합정,합정,합정동,자연에 둘러쌓여 있는듯한 색다른 기분도 느낄수있었고~ 시그니처 오믈렛 정말 맛있었어...,NaN,NaN
4,어반플랜트 합정,합정,합정동,직원분이 테이블링을 도와주셔서 웨이팅을 하다보면 이름을 불러주세요~ 음료도 맛있었고...,NaN,NaN
5,어반플랜트 합정,합정,합정동,카페 인테리어도 예쁘고 이름에 걸맞게 식물들이 많아서 좋았습니다. 특히 건물 외부에...,NaN,NaN
6,포비 베이직,합정,합정동,이제 서울에 꽤나 많은 포비 매장이 생겼지만 역시나 최고는 포비 베이직 합정 매장입...,NaN,NaN
7,포비 베이직,합정,합정동,요기 빛도 너무 좋구 인테리어도 이쁘구 참새도 있음!!! 참새 너무 익숙하게 빵 얻...,NaN,NaN
8,포비 베이직,합정,합정동,주말이나 저녁에 가보다가 평일 낮에 방문하니 너무 좋더라구요! 그것도 봄!! 여유 ...,NaN,NaN
9,어썸마운틴,합정,동교동,500m에서 등반 후 먹는 흑임자치즈케이크와 아아 입니다 아이스아메리카노가 산미 없...,NaN,NaN
10,어썸마운틴,합정,동교동,카페가 이쁘고 감각적입니다! 말차파운드는 못먹었지만 얼그레이도 맛있었어요! 토마토바...,NaN,NaN
11,어썸마운틴,합정,동교동,맨날 강아지랑 산책할때마다 지나가는데 사람이 엄청 많습니다 처음에 생겼을때는 사람이...,NaN,NaN
12,943 킹스크로스CAFE,합정,서교동,해리포터 매니아라면 너무나 좋아할 카페입니다 음료도 비싸지만 맛있고 구경하기 재밌어요~,NaN,NaN
13,944 킹스크로스CAFE,합정,서교동,해리포터를 좋아하는 사람과 함께하면 더 좋은 곳!! 해리포터 음악이 계속 나와서 좋...,NaN,NaN
14,945 킹스크로스CAFE,합정,서교동,홍대에서 어떤 카페를 갈까 친구들과 고민을 하던 중 해리포터 카페로 유명해서 선택하...,NaN,NaN
15,샌드커피 논탄토 연남,합정,동교동,카이막이 먹고 싶어서 찾아갔는데ㅠㅠ 저녁에 갔더니 품절이더라구요!! 아쉽긴 했지만 ...,NaN,NaN
16,샌드커피 논탄토 연남,합정,동교동,죤맛 너무 잘 먹었어요 토스트는 더 구워 달라고 할 걸 그랬어요! 더 바삭한게 좋아...,NaN,NaN
17,샌드커피 논탄토 연남,합정,동교동,시원하고 쾌적하고 메뉴 신기 핸드드립 커피 과테말라 좋아요 다음엔 터키식 카이막도 ...,NaN,NaN
18,콜린,합정,서교동,갑자기 걷는데 비가내려서 들어왔어요. 빗소리 들으면서 맥주 한잔 마시고 있는데 넘나...,NaN,NaN
19,콜린,합정,서교동,플라워카페 너무 이뻐요 들어갈때 꽃향기도 좋고 2층도 있고 테라스도 있고 바나나주스...,NaN,NaN
20,콜린,합정,서교동,인절미 크루아상 대존맛탱구리구리ㅜㅜ 향기나는 꽃들에 둘러쌓여 디저트 먹으면서 기분전...,NaN,NaN
21,차곡파티세리,합정,서교동,에스프레소 맛집 원두 기름이 잘 어우러지는 신선한 원두로 갓내린 커피 초콜릿은 더 ...,NaN,NaN
22,차곡파티세리,합정,서교동,케이크가 정말 너무 맛있어요!!! 녹차쉬폰인데 녹차 크림이 정말 진하고 맛있더라구요...,NaN,NaN
23,차곡파티세리,합정,서교동,음료도 맛있구 케이크가 넘 귀여워요~~셀카찍기 좋은 예쁜 곳^^,NaN,NaN
24,브런치가,합정,동교동,크로크햄 치즈와 치킨퀘사디아를 주문했습니다. 치킨 브리또를 먹으려고 했지만 품절이라...,NaN,NaN
25,브런치가,합정,동교동,"음식도 맛있고, 무엇보다 일찍 열어서 저희처럼 일찍 만나는 사람에게 딱이였어요~^^",NaN,NaN
26,브런치가,합정,동교동,야외 테이블 자리마다 싱그러운 분위기. 바람 시원하고 좋아요.직원 분들 친절하시고 ...,NaN,NaN
27,랑데자뷰 홍대점,합정,서교동,매장도 넓고 음료도 맛있어요! 색감이 되게 이뻐 요 ㅎㅎ 특히 한라봉에이드 찐 추천...,NaN,NaN
28,랑데자뷰 홍대점,합정,서교동,커피도 맛있고 분위기도 좋아요 사진찍을 곳도 많고 직원분들이 친절해용>_<,NaN,NaN
29,랑데자뷰 홍대점,합정,서교동,"훌륭훌륭???????? 날이 더워서 에이드 주문했는데 넘 맛있구, 직원들도 친절해요 ??",NaN,NaN
30,1984,합정,동교동,갈 때마다 만석인 1984 출판사 카페♡ 볼거리도 많고 답답하지 않은 분위기라 편해요!,NaN,NaN
31,1984,합정,동교동,분위기도 힙하고 샌드위치가 맛있네요 레몬에이드는 양 많고 레몬이 가득이라 좋았어요,NaN,NaN
32,1984,합정,동교동,다양한 메뉴가 있고 또 책이나 옷 신발 굿즈까지 있 어서 너무 신기해요 샌드위치 너...,NaN,NaN
33,얀 쿠브레,합정,동교동,요기 첨왔는데 왜 사람이 많은지 알겠네요 진짜 디저트도 딴곳에서 볼수없는 메뉴들이랑...,NaN,NaN
34,얀 쿠브레,합정,동교동,느끼하지도 않고 너무 달지도 않은 디저트 맛집입니다. 포장이 예뻐서 선물하기도 좋습니다.,NaN,NaN
35,얀 쿠브레,합정,동교동,디져트 가격에 놀래서... 저렴이 들로만 구매 했어요~ 커피는 아이스라떼로~ 사람 ...,NaN,NaN
36,앤트러사이트 합정점,합정,합정동,매장이 완전 분위기 있어요~ 1층은 대화하기 좋고 2 층은 공부하기 좋은 분위기네요...,NaN,NaN
37,앤트러사이트 합정점,합정,합정동,1. 힙한 음악 여기 음악 개쩜. 음악 일가견 있다면 여기 음악들 힙하다는걸 듣자마...,NaN,NaN
38,앤트러사이트 합정점,합정,합정동,드립커피 마시러 간혹 다니는 카페에요! 저녁 9시 정도에 가서 이미 드립은 마감이라...,NaN,NaN
39,빈브라더스 합정,합정,합정동,커피도 다 맛있고 디저트도 정말 맛있어요. 특히 스콘이 심플하면서도 겉은 바삭하고 ...,NaN,NaN
40,빈브라더스 합정,합정,합정동,"커피 맛있어요~ 전문가의 맛이죠~ 원래 유명한 곳이었구요~ 빵도 맛있구요~ 다만, ...",NaN,NaN
41,빈브라더스 합정,합정,합정동,옥션 테이스팅 코스) 커피를 내려마신지 얼마 안돼서 이런 비싼 커피를 마셔도 맛을 ...,NaN,NaN
42,리피 메세나폴리스점,합정,서교동,"합정역 브런치맛집, 깔끔한인테리어, 모임장소로 추 천 주차지원가능 잠봉뵈르 맛있음,...",NaN,NaN
43,리피 메세나폴리스점,합정,서교동,인테리어도 이쁘고 브런치도 기대이상이었어요! 넘 이쁘게 나와서 기분좋고~ 올타임 클...,NaN,NaN
44,리피 메세나폴리스점,합정,서교동,음식 따뜻하게 잘나왔구 다 맛있었어용!!!!! 후무스샐러드처음먹는데 굳굳이네욤! 저...,NaN,NaN
45,허밍벨라,합정,서교동,"야외석부터 1,2층여유롭고 배가불러ㅜ디저트맛집 디저트못먹규가용 ㅜㅜ 망코!! 요건 ...",NaN,NaN
46,허밍벨라,합정,서교동,디저트 맛있어요?? 외부 테이블에서 마셨는데 날씨도 좋구 즐거웠어요??,NaN,NaN
47,허밍벨라,합정,서교동,루프탑? 이라고 할 수 있을 것 같음 일단 접근성이 좋고 두번째 방문인데 맛은 없음...,NaN,NaN
48,마가렛리버,합정,합정동,밀크티 머스캣향나고 넘 좋았어용 좌석도 편하고 테라스 캠핑느낌으로 되어있어서 아주 ...,NaN,NaN
49,마가렛리버,합정,합정동,카페가 아기자기해요ㅋㅋ,NaN,NaN
50,마가렛리버,합정,합정동,스콘맛집이어요??,NaN,NaN
51,트래블메이커,합정,동교동,아메리칸식 브런치로 딱 좋은 곳!! 간단히 한 끼 먹기 좋습니다~^^ 평범한 블랙퍼...,NaN,NaN
52,트래블메이커,합정,동교동,브런치가 맛있어 보여서 찾아갔는데 가성비도 좋고 매장 자체부터 미국 느낌 낭낭해요~,NaN,NaN
53,트래블메이커,합정,동교동,아침에 여유롭게 먹다가융????,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN

# 리뷰 데이터셋과 user데이터셋

#### 리뷰 데이터셋과 user데이터셋의 내용에서 Who(이름)을 통해서 수월하게 추천하기 위해서 설정해준다

In [287]:
df['who'] = 'netizen'
df
# 나중에 검색 결과 때문에 who라는 속성을 만들어주었다.

,cafe_name,quary,region,evaluation,rating,coffee_price,who
0,umoae,합정,서교동,인테리어가 감각적이라고 느꼈습니다 사장님이 친절하시고 디저트가 맛있어요 소르베도 재...,NaN,NaN,netizen
1,umoae,합정,서교동,커피와 디저트 모두 너무 맛있어요 가게 분위기도 원목 가구를 써서 그런지 단정하고 ...,NaN,NaN,netizen
2,umoae,합정,서교동,프렌치토스트 소문대로 존맛탱,NaN,NaN,netizen
3,어반플랜트 합정,합정,합정동,자연에 둘러쌓여 있는듯한 색다른 기분도 느낄수있었고~ 시그니처 오믈렛 정말 맛있었어...,NaN,NaN,netizen
4,어반플랜트 합정,합정,합정동,직원분이 테이블링을 도와주셔서 웨이팅을 하다보면 이름을 불러주세요~ 음료도 맛있었고...,NaN,NaN,netizen
5,어반플랜트 합정,합정,합정동,카페 인테리어도 예쁘고 이름에 걸맞게 식물들이 많아서 좋았습니다. 특히 건물 외부에...,NaN,NaN,netizen
6,포비 베이직,합정,합정동,이제 서울에 꽤나 많은 포비 매장이 생겼지만 역시나 최고는 포비 베이직 합정 매장입...,NaN,NaN,netizen
7,포비 베이직,합정,합정동,요기 빛도 너무 좋구 인테리어도 이쁘구 참새도 있음!!! 참새 너무 익숙하게 빵 얻...,NaN,NaN,netizen
8,포비 베이직,합정,합정동,주말이나 저녁에 가보다가 평일 낮에 방문하니 너무 좋더라구요! 그것도 봄!! 여유 ...,NaN,NaN,netizen
9,어썸마운틴,합정,동교동,500m에서 등반 후 먹는 흑임자치즈케이크와 아아 입니다 아이스아메리카노가 산미 없...,NaN,NaN,netizen
10,어썸마운틴,합정,동교동,카페가 이쁘고 감각적입니다! 말차파운드는 못먹었지만 얼그레이도 맛있었어요! 토마토바...,NaN,NaN,netizen
11,어썸마운틴,합정,동교동,맨날 강아지랑 산책할때마다 지나가는데 사람이 엄청 많습니다 처음에 생겼을때는 사람이...,NaN,NaN,netizen
12,943 킹스크로스CAFE,합정,서교동,해리포터 매니아라면 너무나 좋아할 카페입니다 음료도 비싸지만 맛있고 구경하기 재밌어요~,NaN,NaN,netizen
13,944 킹스크로스CAFE,합정,서교동,해리포터를 좋아하는 사람과 함께하면 더 좋은 곳!! 해리포터 음악이 계속 나와서 좋...,NaN,NaN,netizen
14,945 킹스크로스CAFE,합정,서교동,홍대에서 어떤 카페를 갈까 친구들과 고민을 하던 중 해리포터 카페로 유명해서 선택하...,NaN,NaN,netizen
15,샌드커피 논탄토 연남,합정,동교동,카이막이 먹고 싶어서 찾아갔는데ㅠㅠ 저녁에 갔더니 품절이더라구요!! 아쉽긴 했지만 ...,NaN,NaN,netizen
16,샌드커피 논탄토 연남,합정,동교동,죤맛 너무 잘 먹었어요 토스트는 더 구워 달라고 할 걸 그랬어요! 더 바삭한게 좋아...,NaN,NaN,netizen
17,샌드커피 논탄토 연남,합정,동교동,시원하고 쾌적하고 메뉴 신기 핸드드립 커피 과테말라 좋아요 다음엔 터키식 카이막도 ...,NaN,NaN,netizen
18,콜린,합정,서교동,갑자기 걷는데 비가내려서 들어왔어요. 빗소리 들으면서 맥주 한잔 마시고 있는데 넘나...,NaN,NaN,netizen
19,콜린,합정,서교동,플라워카페 너무 이뻐요 들어갈때 꽃향기도 좋고 2층도 있고 테라스도 있고 바나나주스...,NaN,NaN,netizen
20,콜린,합정,서교동,인절미 크루아상 대존맛탱구리구리ㅜㅜ 향기나는 꽃들에 둘러쌓여 디저트 먹으면서 기분전...,NaN,NaN,netizen
21,차곡파티세리,합정,서교동,에스프레소 맛집 원두 기름이 잘 어우러지는 신선한 원두로 갓내린 커피 초콜릿은 더 ...,NaN,NaN,netizen
22,차곡파티세리,합정,서교동,케이크가 정말 너무 맛있어요!!! 녹차쉬폰인데 녹차 크림이 정말 진하고 맛있더라구요...,NaN,NaN,netizen
23,차곡파티세리,합정,서교동,음료도 맛있구 케이크가 넘 귀여워요~~셀카찍기 좋은 예쁜 곳^^,NaN,NaN,netizen
24,브런치가,합정,동교동,크로크햄 치즈와 치킨퀘사디아를 주문했습니다. 치킨 브리또를 먹으려고 했지만 품절이라...,NaN,NaN,netizen
25,브런치가,합정,동교동,"음식도 맛있고, 무엇보다 일찍 열어서 저희처럼 일찍 만나는 사람에게 딱이였어요~^^",NaN,NaN,netizen
26,브런치가,합정,동교동,야외 테이블 자리마다 싱그러운 분위기. 바람 시원하고 좋아요.직원 분들 친절하시고 ...,NaN,NaN,netizen
27,랑데자뷰 홍대점,합정,서교동,매장도 넓고 음료도 맛있어요! 색감이 되게 이뻐 요 ㅎㅎ 특히 한라봉에이드 찐 추천...,NaN,NaN,netizen
28,랑데자뷰 홍대점,합정,서교동,커피도 맛있고 분위기도 좋아요 사진찍을 곳도 많고 직원분들이 친절해용>_<,NaN,NaN,netizen
29,랑데자뷰 홍대점,합정,서교동,"훌륭훌륭???????? 날이 더워서 에이드 주문했는데 넘 맛있구, 직원들도 친절해요 ??",NaN,NaN,netizen
30,1984,합정,동교동,갈 때마다 만석인 1984 출판사 카페♡ 볼거리도 많고 답답하지 않은 분위기라 편해요!,NaN,NaN,netizen
31,1984,합정,동교동,분위기도 힙하고 샌드위치가 맛있네요 레몬에이드는 양 많고 레몬이 가득이라 좋았어요,NaN,NaN,netizen
32,1984,합정,동교동,다양한 메뉴가 있고 또 책이나 옷 신발 굿즈까지 있 어서 너무 신기해요 샌드위치 너...,NaN,NaN,netizen
33,얀 쿠브레,합정,동교동,요기 첨왔는데 왜 사람이 많은지 알겠네요 진짜 디저트도 딴곳에서 볼수없는 메뉴들이랑...,NaN,NaN,netizen
34,얀 쿠브레,합정,동교동,느끼하지도 않고 너무 달지도 않은 디저트 맛집입니다. 포장이 예뻐서 선물하기도 좋습니다.,NaN,NaN,netizen
35,얀 쿠브레,합정,동교동,디져트 가격에 놀래서... 저렴이 들로만 구매 했어요~ 커피는 아이스라떼로~ 사람 ...,NaN,NaN,netizen
36,앤트러사이트 합정점,합정,합정동,매장이 완전 분위기 있어요~ 1층은 대화하기 좋고 2 층은 공부하기 좋은 분위기네요...,NaN,NaN,netizen
37,앤트러사이트 합정점,합정,합정동,1. 힙한 음악 여기 음악 개쩜. 음악 일가견 있다면 여기 음악들 힙하다는걸 듣자마...,NaN,NaN,netizen
38,앤트러사이트 합정점,합정,합정동,드립커피 마시러 간혹 다니는 카페에요! 저녁 9시 정도에 가서 이미 드립은 마감이라...,NaN,NaN,netizen
39,빈브라더스 합정,합정,합정동,커피도 다 맛있고 디저트도 정말 맛있어요. 특히 스콘이 심플하면서도 겉은 바삭하고 ...,NaN,NaN,netizen
40,빈브라더스 합정,합정,합정동,"커피 맛있어요~ 전문가의 맛이죠~ 원래 유명한 곳이었구요~ 빵도 맛있구요~ 다만, ...",NaN,NaN,netizen
41,빈브라더스 합정,합정,합정동,옥션 테이스팅 코스) 커피를 내려마신지 얼마 안돼서 이런 비싼 커피를 마셔도 맛을 ...,NaN,NaN,netizen
42,리피 메세나폴리스점,합정,서교동,"합정역 브런치맛집, 깔끔한인테리어, 모임장소로 추 천 주차지원가능 잠봉뵈르 맛있음,...",NaN,NaN,netizen
43,리피 메세나폴리스점,합정,서교동,인테리어도 이쁘고 브런치도 기대이상이었어요! 넘 이쁘게 나와서 기분좋고~ 올타임 클...,NaN,NaN,netizen
44,리피 메세나폴리스점,합정,서교동,음식 따뜻하게 잘나왔구 다 맛있었어용!!!!! 후무스샐러드처음먹는데 굳굳이네욤! 저...,NaN,NaN,netizen
45,허밍벨라,합정,서교동,"야외석부터 1,2층여유롭고 배가불러ㅜ디저트맛집 디저트못먹규가용 ㅜㅜ 망코!! 요건 ...",NaN,NaN,netizen
46,허밍벨라,합정,서교동,디저트 맛있어요?? 외부 테이블에서 마셨는데 날씨도 좋구 즐거웠어요??,NaN,NaN,netizen
47,허밍벨라,합정,서교동,루프탑? 이라고 할 수 있을 것 같음 일단 접근성이 좋고 두번째 방문인데 맛은 없음...,NaN,NaN,netizen
48,마가렛리버,합정,합정동,밀크티 머스캣향나고 넘 좋았어용 좌석도 편하고 테라스 캠핑느낌으로 되어있어서 아주 ...,NaN,NaN,netizen
49,마가렛리버,합정,합정동,카페가 아기자기해요ㅋㅋ,NaN,NaN,netizen
50,마가렛리버,합정,합정동,스콘맛집이어요??,NaN,NaN,netizen
51,트래블메이커,합정,동교동,아메리칸식 브런치로 딱 좋은 곳!! 간단히 한 끼 먹기 좋습니다~^^ 평범한 블랙퍼...,NaN,NaN,netizen
52,트래블메이커,합정,동교동,브런치가 맛있어 보여서 찾아갔는데 가성비도 좋고 매장 자체부터 미국 느낌 낭낭해요~,NaN,NaN,netizen
53,트래블메이커,합정,동교동,아침에 여유롭게 먹다가융????,NaN,NaN,netizen
54,NaN,NaN,NaN,NaN,NaN,NaN,netizen

#### 설문지

https://docs.google.com/forms/d/1NpMqjm_irWul-KTW8gLywuWKiSaeBKBMwZFVgc_Ikec/edit?hl=ko

In [286]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [237]:
'''
user = pd.read_csv('/content/drive/MyDrive/datagit/data/Find your favorite cafe 2.csv')
user = user.drop(['타임스탬프'], axis = 1)
user.columns = ['quary', 'region', 'evaluation', 'who']
user
'''

  quary region                             evaluation   who
0   합정역    서교동  맛있는 디저트와 특이한 컨셉의 인테리어 카페에서 커피를 마시고싶어요  Eden

In [247]:
# pd.concat([df, user])

,cafe_name,quary,region,evaluation,rating,coffee_price
who,,,,,,
netizen,umoae,합정,서교동,인테리어가 감각적이라고 느꼈습니다 사장님이 친절하시고 디저트가 맛있어요 소르베도 재...,NaN,NaN
netizen,umoae,합정,서교동,커피와 디저트 모두 너무 맛있어요 가게 분위기도 원목 가구를 써서 그런지 단정하고 ...,NaN,NaN
netizen,umoae,합정,서교동,프렌치토스트 소문대로 존맛탱,NaN,NaN
netizen,어반플랜트 합정,합정,합정동,자연에 둘러쌓여 있는듯한 색다른 기분도 느낄수있었고~ 시그니처 오믈렛 정말 맛있었어...,NaN,NaN
netizen,어반플랜트 합정,합정,합정동,직원분이 테이블링을 도와주셔서 웨이팅을 하다보면 이름을 불러주세요~ 음료도 맛있었고...,NaN,NaN
netizen,어반플랜트 합정,합정,합정동,카페 인테리어도 예쁘고 이름에 걸맞게 식물들이 많아서 좋았습니다. 특히 건물 외부에...,NaN,NaN
netizen,포비 베이직,합정,합정동,이제 서울에 꽤나 많은 포비 매장이 생겼지만 역시나 최고는 포비 베이직 합정 매장입...,NaN,NaN
netizen,포비 베이직,합정,합정동,요기 빛도 너무 좋구 인테리어도 이쁘구 참새도 있음!!! 참새 너무 익숙하게 빵 얻...,NaN,NaN
netizen,포비 베이직,합정,합정동,주말이나 저녁에 가보다가 평일 낮에 방문하니 너무 좋더라구요! 그것도 봄!! 여유 ...,NaN,NaN
netizen,어썸마운틴,합정,동교동,500m에서 등반 후 먹는 흑임자치즈케이크와 아아 입니다 아이스아메리카노가 산미 없...,NaN,NaN
netizen,어썸마운틴,합정,동교동,카페가 이쁘고 감각적입니다! 말차파운드는 못먹었지만 얼그레이도 맛있었어요! 토마토바...,NaN,NaN
netizen,어썸마운틴,합정,동교동,맨날 강아지랑 산책할때마다 지나가는데 사람이 엄청 많습니다 처음에 생겼을때는 사람이...,NaN,NaN
netizen,943 킹스크로스CAFE,합정,서교동,해리포터 매니아라면 너무나 좋아할 카페입니다 음료도 비싸지만 맛있고 구경하기 재밌어요~,NaN,NaN
netizen,944 킹스크로스CAFE,합정,서교동,해리포터를 좋아하는 사람과 함께하면 더 좋은 곳!! 해리포터 음악이 계속 나와서 좋...,NaN,NaN
netizen,945 킹스크로스CAFE,합정,서교동,홍대에서 어떤 카페를 갈까 친구들과 고민을 하던 중 해리포터 카페로 유명해서 선택하...,NaN,NaN
netizen,샌드커피 논탄토 연남,합정,동교동,카이막이 먹고 싶어서 찾아갔는데ㅠㅠ 저녁에 갔더니 품절이더라구요!! 아쉽긴 했지만 ...,NaN,NaN
netizen,샌드커피 논탄토 연남,합정,동교동,죤맛 너무 잘 먹었어요 토스트는 더 구워 달라고 할 걸 그랬어요! 더 바삭한게 좋아...,NaN,NaN
netizen,샌드커피 논탄토 연남,합정,동교동,시원하고 쾌적하고 메뉴 신기 핸드드립 커피 과테말라 좋아요 다음엔 터키식 카이막도 ...,NaN,NaN
netizen,콜린,합정,서교동,갑자기 걷는데 비가내려서 들어왔어요. 빗소리 들으면서 맥주 한잔 마시고 있는데 넘나...,NaN,NaN
netizen,콜린,합정,서교동,플라워카페 너무 이뻐요 들어갈때 꽃향기도 좋고 2층도 있고 테라스도 있고 바나나주스...,NaN,NaN
netizen,콜린,합정,서교동,인절미 크루아상 대존맛탱구리구리ㅜㅜ 향기나는 꽃들에 둘러쌓여 디저트 먹으면서 기분전...,NaN,NaN
netizen,차곡파티세리,합정,서교동,에스프레소 맛집 원두 기름이 잘 어우러지는 신선한 원두로 갓내린 커피 초콜릿은 더 ...,NaN,NaN
netizen,차곡파티세리,합정,서교동,케이크가 정말 너무 맛있어요!!! 녹차쉬폰인데 녹차 크림이 정말 진하고 맛있더라구요...,NaN,NaN
netizen,차곡파티세리,합정,서교동,음료도 맛있구 케이크가 넘 귀여워요~~셀카찍기 좋은 예쁜 곳^^,NaN,NaN
netizen,브런치가,합정,동교동,크로크햄 치즈와 치킨퀘사디아를 주문했습니다. 치킨 브리또를 먹으려고 했지만 품절이라...,NaN,NaN
netizen,브런치가,합정,동교동,"음식도 맛있고, 무엇보다 일찍 열어서 저희처럼 일찍 만나는 사람에게 딱이였어요~^^",NaN,NaN
netizen,브런치가,합정,동교동,야외 테이블 자리마다 싱그러운 분위기. 바람 시원하고 좋아요.직원 분들 친절하시고 ...,NaN,NaN
netizen,랑데자뷰 홍대점,합정,서교동,매장도 넓고 음료도 맛있어요! 색감이 되게 이뻐 요 ㅎㅎ 특히 한라봉에이드 찐 추천...,NaN,NaN
netizen,랑데자뷰 홍대점,합정,서교동,커피도 맛있고 분위기도 좋아요 사진찍을 곳도 많고 직원분들이 친절해용>_<,NaN,NaN
netizen,랑데자뷰 홍대점,합정,서교동,"훌륭훌륭???????? 날이 더워서 에이드 주문했는데 넘 맛있구, 직원들도 친절해요 ??",NaN,NaN
netizen,1984,합정,동교동,갈 때마다 만석인 1984 출판사 카페♡ 볼거리도 많고 답답하지 않은 분위기라 편해요!,NaN,NaN
netizen,1984,합정,동교동,분위기도 힙하고 샌드위치가 맛있네요 레몬에이드는 양 많고 레몬이 가득이라 좋았어요,NaN,NaN
netizen,1984,합정,동교동,다양한 메뉴가 있고 또 책이나 옷 신발 굿즈까지 있 어서 너무 신기해요 샌드위치 너...,NaN,NaN
netizen,얀 쿠브레,합정,동교동,요기 첨왔는데 왜 사람이 많은지 알겠네요 진짜 디저트도 딴곳에서 볼수없는 메뉴들이랑...,NaN,NaN
netizen,얀 쿠브레,합정,동교동,느끼하지도 않고 너무 달지도 않은 디저트 맛집입니다. 포장이 예뻐서 선물하기도 좋습니다.,NaN,NaN
netizen,얀 쿠브레,합정,동교동,디져트 가격에 놀래서... 저렴이 들로만 구매 했어요~ 커피는 아이스라떼로~ 사람 ...,NaN,NaN
netizen,앤트러사이트 합정점,합정,합정동,매장이 완전 분위기 있어요~ 1층은 대화하기 좋고 2 층은 공부하기 좋은 분위기네요...,NaN,NaN
netizen,앤트러사이트 합정점,합정,합정동,1. 힙한 음악 여기 음악 개쩜. 음악 일가견 있다면 여기 음악들 힙하다는걸 듣자마...,NaN,NaN
netizen,앤트러사이트 합정점,합정,합정동,드립커피 마시러 간혹 다니는 카페에요! 저녁 9시 정도에 가서 이미 드립은 마감이라...,NaN,NaN
netizen,빈브라더스 합정,합정,합정동,커피도 다 맛있고 디저트도 정말 맛있어요. 특히 스콘이 심플하면서도 겉은 바삭하고 ...,NaN,NaN
netizen,빈브라더스 합정,합정,합정동,"커피 맛있어요~ 전문가의 맛이죠~ 원래 유명한 곳이었구요~ 빵도 맛있구요~ 다만, ...",NaN,NaN
netizen,빈브라더스 합정,합정,합정동,옥션 테이스팅 코스) 커피를 내려마신지 얼마 안돼서 이런 비싼 커피를 마셔도 맛을 ...,NaN,NaN
netizen,리피 메세나폴리스점,합정,서교동,"합정역 브런치맛집, 깔끔한인테리어, 모임장소로 추 천 주차지원가능 잠봉뵈르 맛있음,...",NaN,NaN
netizen,리피 메세나폴리스점,합정,서교동,인테리어도 이쁘고 브런치도 기대이상이었어요! 넘 이쁘게 나와서 기분좋고~ 올타임 클...,NaN,NaN
netizen,리피 메세나폴리스점,합정,서교동,음식 따뜻하게 잘나왔구 다 맛있었어용!!!!! 후무스샐러드처음먹는데 굳굳이네욤! 저...,NaN,NaN
netizen,허밍벨라,합정,서교동,"야외석부터 1,2층여유롭고 배가불러ㅜ디저트맛집 디저트못먹규가용 ㅜㅜ 망코!! 요건 ...",NaN,NaN
netizen,허밍벨라,합정,서교동,디저트 맛있어요?? 외부 테이블에서 마셨는데 날씨도 좋구 즐거웠어요??,NaN,NaN
netizen,허밍벨라,합정,서교동,루프탑? 이라고 할 수 있을 것 같음 일단 접근성이 좋고 두번째 방문인데 맛은 없음...,NaN,NaN
netizen,마가렛리버,합정,합정동,밀크티 머스캣향나고 넘 좋았어용 좌석도 편하고 테라스 캠핑느낌으로 되어있어서 아주 ...,NaN,NaN
netizen,마가렛리버,합정,합정동,카페가 아기자기해요ㅋㅋ,NaN,NaN
netizen,마가렛리버,합정,합정동,스콘맛집이어요??,NaN,NaN
netizen,트래블메이커,합정,동교동,아메리칸식 브런치로 딱 좋은 곳!! 간단히 한 끼 먹기 좋습니다~^^ 평범한 블랙퍼...,NaN,NaN
netizen,트래블메이커,합정,동교동,브런치가 맛있어 보여서 찾아갔는데 가성비도 좋고 매장 자체부터 미국 느낌 낭낭해요~,NaN,NaN
netizen,트래블메이커,합정,동교동,아침에 여유롭게 먹다가융????,NaN,NaN
netizen,NaN,NaN,NaN,NaN,NaN,NaN
Eden,NaN,합정역,서교동,맛있는 디저트와 특이한 컨셉의 인테리어 카페에서 커피를 마시고싶어요,NaN,NaN

#### 리뷰 데이터에 대한 자연어처리를 위해서 데이터 전처리를 실시해준다.

In [288]:
import re

re.compile('[^가-힣]')을 사용할 때 string으로 변환해줘야합니다.

In [289]:
def extract_word(text):
    hangul = re.compile('[^가-힣]')
    result = hangul.sub(' ', text) 
    return result

In [290]:
len(df)

55

In [291]:
extract_word(df['evaluation'][19])

'플라워카페 너무 이뻐요 들어갈때 꽃향기도 좋고  층도 있고 테라스도 있고 바나나주스 진짜 맛있었어요 딸기 케이크는 조금 더 달았으면 좋겠어요 굿굿'

In [292]:
extract_word(df['evaluation'][19])
' '.join(df['evaluation'][19].split())

'플라워카페 너무 이뻐요 들어갈때 꽃향기도 좋고 2층도 있고 테라스도 있고 바나나주스 진짜 맛있었어요 딸기 케이크는 조금 더 달았으면 좋겠어요 굿굿'

In [293]:
df['evaluation'] = df['evaluation'].apply(lambda x : extract_word(str(x)))

#### 카페 이름별 evalution 내용들 하나로 통합
카페 이름별 평가를 각각 만들어주었는데, 나중에 중복으로 추천해주는 것을 방지해주기 위해서 하나의 문장 or 하나의 평가처럼 통합할 필요가 있을 것 같다

In [294]:
df.loc[len(df)-1] = ['NaN', '합정', '서교동', '햇빛 따스한 외부에서 커피 한잔', 'NaN', 'NaN', 'eden']
df['evaluation'][54] # if, user data

'햇빛 따스한 외부에서 커피 한잔'

In [295]:
target_text = df['evaluation'].iloc[54]
target_text

'햇빛 따스한 외부에서 커피 한잔'

# 띄어쓰기 전처리 및 한글 띄어쓰기 해결하기

#### PyKoSpacing!

한국어 띄어쓰기 패키지로 띄어쓰기가 되어있지 않은 문장을 띄어쓰기를 한 문장으로 변환해주는 패키지

In [ ]:
# !pip install git+https://github.com/haven-jeon/PyKoSpacing.git

#### Py-Hanspell
네이버 한글 맞춤법 검사기를 바탕으로 만들어진 패키지로써 맞춤법을 고친 문장을 반환하도록 해줍니다.

In [ ]:
# !pip install git+https://github.com/ssut/py-hanspell.git

In [296]:
from pykospacing import Spacing
spacing = Spacing()

In [297]:
from hanspell import spell_checker
for i in range(1,len(df)):
    spelled_sent = spell_checker.check(df['evaluation'][i])
    spell = spelled_sent.checked
    df['evaluation'][i] = spacing(spell)
    print(df['evaluation'][i])

커피와 디저트 모두 너무 맛있어요 가게 분위기도 원목 가구를 써서 그런지 단정하고 대화하기 좋았어요 의자는 참 무겁더라고요 집어넣고 가기엔 쉽지 않았네요 늦게까지 영업해서 오래간 만에 회포 풀기도 좋았고 커피 향이 참 좋았습니다
프렌치 토스트 소문대로 존 맛탱
자연에 둘러싸여 있는 듯한 색다른 기분도 느낄 수 있었고 시그니처 오믈렛 정말 맛 있었어요 스파게티류는 면류가 없어서 아쉬웠지만 음식 맛은 괜춘 무엇보다 분위기가 너무 좋았어요 위치는 합정이었지만 그 안에 들어가면 멀리 근교에 나와 있는 듯한 기분을 느끼고 왔습니다
직원분이 테이블 리을 도와 주셔서 웨이팅을 하다 보면 이름을 불러주세요 음료도 맛있었고 구성비가 좋았던 것 같아 요 개인적으로 매장 내에 식물이 많아서 풀 냄새가 나서 좋았어요 담번에는 브런치를 먹으러 갈래요
카페 인테리어도 예쁘고 이름에 걸 맞게 식물들이 많아서 좋았습니다 특히 건물 외부에도 자리를 많이 만들어 두어서 날이 좋을 때 애 이용하면 좋을 것 같아 요 브런치 메뉴의 금액 대는 조금 높은 편이지만 매우 만족했던 첫 방문이었습니다
이제 서울에 꽤나 많은 포비 매장이 생겼지만 역시나 최고는 포비 베이직 합정 매장입니다 통유리 건물을 통째로 사용하고 있어 건물 외관도 예쁘고
요기 빛도 너무 좋고 인테리어도 이 쁘고 참새도 있음 참새 너무 익숙하게 빵 얻어먹는 커피 맛있고 러스크 가격 좀 사악하지만 정말 매우 흔하고 아는 그 맛인데 돈 주고 사 먹는 그 맛있는 맛 다른 지점들도 가봐야지
주말이나 저녁에 가보다가 평일 낮에 방문하니 너무 좋더라고요 그것도 봄 여유 있고 정말 커피는 말 할 것도 없이 맛있고 피콜로를 좋아합니다 베이글도 크림치즈 없이도 너무 맛있는 것 따로 구매할 수 있음
에서 등반 후 먹는 흑임자 치즈케이크와 아입니다 아이스 아메리카노가 산 미 없고 고소하고 묵직한 맛이 납니다 그리고 흑임자 치즈케이크 산 모양으로 겉 모습은 퍼석할 거 같았는데 촉촉하고 요 그리고 되게 고소해 요 치즈를 잘 못 먹는데 맛있게 잘 먹었어요 인기 진짜 많아요 사람도 많고요 혹시 여유롭게 카페에서 작업을 하러 가 실 땐 평일 날을 추천 드립니다  주말은 친구들과 수 다 떨러 오시는 게 좋을 듯해요
카페가 이 쁘고 감각적입니다 말 차 파운드는 못 먹었지만 얼 그레이도 맛있었어요 토마토 바질 에이드 기대했는데 생각이랑 다른 맛이었지만 좋았어요 바질 좋아해서 진짜 괜찮았어요 토마토 맛보다는 바질 향이 진한 느낌이라 깔끔했어요 커피도 너무 산미가 있거나 너무 탄 맛나는 게 아니고 딱 중간이라 좋았습니다 퀸 주호 님 친절하세요
맨날 강아지랑 산책할 때마다 지나가는데 사람이 엄청 많습니다 처음에 생겼을 때는 사람이 많지 않아서 강아지랑 지나가다가 들어오고 그랬었는데 이제는 너무나 핫 플이 되어버렸네요 평일에 일찍 오픈 시간에 오니 매장 사진도 실컷 찍고 편안한 커피타임을 가졌습니다 어 썸 커피 존 맛뱅이에 용 커피 디저트 분위기 다 가진 핫 플레이스
해리포터 마니아라면 너무나 좋아할 카페입니다 음료도 비싸지만 맛있고 구경하기 재밌어요
해리 포터를 좋아하는 사람과 함께 하면 더 좋은 곳 해리포터 음악이 계속 나와서 좋았어요
홍대에서 어떤 카페를 갈까 친구들과 고민을 하던 중 해리포터 카페로 유명해서 선택하게 되었습니다 저도 다른 사람들과 다르지 않게 리뷰를 검색하고 결정을 하는 편인데 맛에 대해서 평가가 좋은 편이 아니라 중간에 조금 고민도 되었습니다 직접 가본 결과 저에게는 그럭저럭 무난했습니다 맛보다는 인테리어에 너무나도 매혹되었습니다 입장료를 내고 전시회를 다 녀온 기분이었어요 사진 찍는 것을 좋아하시는 분 평범한 인테리어보다는 조금 더 유니크한 인테리어를 좋아하시는 분들께 강력하게 추천드려요 진짜 친구들과 재밌게 다양한 콘셉트로 사진을 찍어볼 수 있어서 너무 좋았습니다
칼이 막이 먹고 싶어서 찾아갔는데 저녁에 갔더니 품절이더라고요 아쉽긴 했지만 카페가 조용하니 좋아서 커피라도 마시고 왔습니다 체증 베는 처음 접해 보는데 생각보다 먹을 만했어요 마실 때 조금씩 섞여 들어오는 원두 가루가 그렇게 거부감 들지 않아서 그런 가 홀짝홀짝 잘 마셨어요 다음엔 좀 일찍 가서 칼이 막까지 즐기고 오려고 요
죤 맛 너무 잘 먹었어요 토스트는 더 구워 달라고 할 걸 그랬어요 더 바삭한 게 좋아서 골든 크림 라테는 생각보다 라테에서 산미가 느껴졌어요 제 취향은 아니었는데 그래도 칼이 막 너무 잘 먹었어요
시원하고 쾌적하고 메뉴 신기 핸드드립 커피 과 테말라 좋아요 다음엔 터키식 카이 막도 먹어볼게요
갑자기 걷는데 비가 내려서 들어왔어요 빗소리 들으면서 맥주 한 잔 마시고 있는데 너무나 좋아요
플라워 카페 너무 이 뻐요 들어갈 때 꽃 향기도 좋고 층도 있고 테라스도 있고 바나나 주스 진짜 맛있었어요 딸기 케이크는 조금 더 달았으면 좋겠어요 굿굿
인절미 크루아상 대존 맛 탱구리구리 향기 나는 꽃들에 둘러싸여 디저트 먹으면서 기 분전환 지대로 했어요
에스프레소 맛집 원두 기름이 잘 어우러지는 신선한 원두로 갓 내린 커피 초콜릿은 더 맛있다 에 스프레 소 좋아하시는 분의 추천으로 발견한 커피 맛
케이크가 정말 너무 맛있어요 녹차 시폰인 데 녹차 크림이 정말 진하고 맛있더라고요 진짜 케이크 정말 강 추합니다
음료도 맛있고 케이크가 너무 귀여워요 셀카 찍기 좋은 예쁜 곳
크로크햄 치즈와 치킨 퀘사디아를 주문했습니다 치킨 브리또를 먹으려고 했지만 품절이라고 브리또와 비슷한 퀘사디아를 추천해주셔서 먹었는데 맛있더군 요 감자튀김도 많이 나오고 정말 배 부르고 맛있게 먹었습니다
음식도 맛있고 무엇보다 일찍 열어서 저희처럼 일찍 만나는 사람에게 딱이었어요
야외 테이블 자리마다 싱 그러운 분위기 바람 시원하고 좋아요 직원 분들 친절하시고 응대 잘 해주셔서 좋고요 메뉴도 구성비 좋고 맛있네요 친구들과 브런치 하기 편하고 여유로운 브런치가
매장도 넓고 음료도 맛있어요 색감이 되게 이 뻐 요 특히 한라봉 에이드 찐 추천 자꾸 생각나는 맛 포토존은 사진도 잘 나오고 사진 찍기도
커피도 맛있고 분위기도 좋아요 사진 찍을 곳도 많고 직원 분들이 친절해요
훌륭훌 륭 날이 더워서 에이드 주문했는데 너무 맛있고 직원들도 친절해요
갈 때마다 만석인 출판사 카페 볼거리도 많고 답답하지 않은 분위기라 편해요
분위기도 히프하고 샌드위치가 맛있네요 레모네이드는 양 많고 레몬이 가득이라 좋았어요
다양한 메뉴가 있고 또 책이나 옷 신발 굿즈까지 있어서 너무 신기해요 샌드위치 너무 맛있고 착즙주스 건강하고 맛있네요 완전히 만족이에요
요기 첨 왔는데 왜 사람이 많은 지 알겠네요 진짜 디저트도 딴 곳에서 볼 수 없는 메뉴들이랑 특별한 곳 같아 용
느끼하지도 않고 너무 달 지도 않은 디저트 맛 집입니다 포장이 예뻐서 선물하기도 좋습니다
디저트 가격에 놀라서 저렴이 들로만 구매했어요 커피는 아이스 라테로 사람 많아요
매장이 완전 분위기 있어요 층은 대화하기 좋고 층은 공부하기 좋은 분위기네요 너티 크림 첫 맛은 좀 쓰지만 마실수록 오틀리 밀크가 올라와서 고소
힙한 음악 여기 음악 개쩜 음악 일가 견 있다면 여기 음악들 히프 하다는 걸 듣자마자 알 거임 힙한 인테리어 정면 분할 스크린 개 힙합 음악과 찰떡 어둑하면서도 은은 한 라이팅이 끝내줌 분할된 공간 위층에는 음악이 안 나와서 공부하는 사람들이 많이 계심 게다가 거긴 테라스도 있음 커피 너티 크림 진짜 개존 맛 단잔의 끝판왕  다음에는 드립 커피도 먹어봐야 겠음
드립 커피 마시러 간혹 다니는 카페에 요 저녁 시 정도에 가서 이미 드립은 마감이라 아메리카노만 마실 수 있었고 최애 원두는 윌리엄 블레이크인데 어제는 요건 선택 불가라 버터 팻 트리오 마셨는데 괜찮았어요 사진에는 설탕인데 왜 이 리 설탕마저 맛있는지 합정점은 매장이 넓고 크고 좌석도 많아서 좋은 것 같아 요 대화하시려면 합정점 추천합니다 망원  쪽에 서교점은 대화도 눈치 보이고 어두워서 잘 안 가게 되더라고요 합정이 좋습니다
커피도 다 맛있고 디저트도 정말 맛있어요 특히 스콘이 심플하면서도 겉은 바삭하고 속은 부드러워요 계속 입에 들어가요 얼그레이 가 또 쇼콜라의 진한 크림은 일 품입니다 살만 안 찐다면 매일 먹고 싶어요
커피 맛있어요 전문가의 맛이 죠 원래 유명한 곳이었고요 빵도 맛있고요 다만 앞에 주차가 공간이 넓지 않아 쉽지는 않아 요
옥션 테이스팅 코스 커피를 내려 마신지 얼마 안 돼서 이런 비싼 커피를 마셔도 맛을 느낄 수 있을까 걱정이 많이 됐는데 바리스타 분께서 자세히 설명도 해주시고 포인트를 잘 잡아주셔서 만족스러웠습니다
합정역 브런치 맛 집 깔끔한 인테리어 모임 장소로 추 천 주차지원 가능 잠봉 뵈르 맛있음 에 그 인 헬 맛있음 봉골 레 다소 비리지만 특이해서 자꾸 당 김 아
인테리어도 이 쁘고 브런치도 기 대 이상이었어요 너무 이쁘게 나와서 기분 좋고 올 타임 클래식 플래터 먹었는데 너무 맛있었어요 다만 직원 분들 너무 바빠 보였네요 담에 또 들르고 싶어요
음식 따뜻하게 잘 나왔고 다 맛있었어요 후 무스 샐러드 처음 먹는데 굳굳이 네 욤 저 라자냐도 에 그인 헬도 굳
야외 석부터 층 여유롭고 배가 불러 디저트 맛 집 디저트 못 먹기가 용 망고 요건 추천요 특별 한 메뉴 다용
디저트 맛있어요 외부 테이블에서 마셨는데 날씨도 좋고 즐거웠어요
루프탑이라고 할 수 있을 것 같음 일단 접근성이 좋고 두 번째 방문인데 맛은 없음 케이크도 모르겠다 크림만 먹었음 빵 맛 없어 성 밖에 앉고 싶다면 오는 거 추천
밀크티 머스캣 양 나 고 너무 좋았어요 좌석도 편하고 테라스 캠핑 느낌으로 되어 있어서 아주 좋았어요
카페가 아기자기해요
스콘 맛 집이어요
아메리칸 시계 브런치로 딱 좋은 곳 간단히 한 끼 먹기 좋습니다 평범한 브렉퍼스트가 그리우시면 안성맞춤이에요
브런치가 맛있어 보여서 찾아갔는데 구성비도 좋고 매장 자체부터 미국 느낌 낭랑해요
아침에 여유롭게 먹다가 융
햇빛 따스한 외부에서 커피 한잔

# 자연어처리 시작

In [ ]:
# !pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: konlpy in /usr/local/lib/python3.7/dist-packages (0.6.0)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.7/dist-packages (from konlpy) (4.2.6)
Requirement already satisfied: JPype1>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from konlpy) (1.4.0)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.7/dist-packages (from konlpy) (1.21.6)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from JPype1>=0.7.0->konlpy) (4.1.1)

In [298]:
from konlpy.tag import Okt
# from konlpy.tag import Mecab
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import TfidfVectorizer

okt = Okt()

In [ ]:
'''
def tokenizer(raw, pos=["NNG","NNP","VV","VA"], stopword = stopwords): 
   
    okt = Okt() 
    return [word for word, tag in okt.pos(raw) if len(word) > 1 and tag in pos and word not in stopword ]
'''

'\ndef tokenizer(raw, pos=["NNG","NNP","VV","VA"], stopword = stopwords): \n   \n    okt = Okt() \n    return [word for word, tag in okt.pos(raw) if len(word) > 1 and tag in pos and word not in stopword ]\n'

In [ ]:
# vectorize = TfidfVectorizer(tokenizer= tokenizer, ngram_range=(1,2), min_df=3 )

In [299]:
for i, document in enumerate(df['evaluation']):
    clean_words = []
    for word in okt.pos(document, stem=True): #어간 추출
        if word[1] in ['Noun', 'Verb','Adjective']: #명사, 동사, 형용사
            clean_words.append(word[0])
    # print(clean_words)
    document = ' '.join(clean_words)
    print(document) 
    df['evaluation'][i] = document

인테리어 감각 느끼다 사장 친절하다 디저트 맛있다 소르베 재미있다
커피 디저트 모두 맛있다 가게 분위기 원목 가구 써다 그렇다 단정하다 대화 하다 좋다 의자 차다 무겁다 집어넣다 가기 쉬다 않다 늦다 영업 하다 간 회포 풀기 좋다 커피 향 차다 좋다
프렌치 토스트 소문 존 맛
자연 둘러싸이다 있다 듯 색다르다 기분 느끼다 수 있다 처 오믈렛 정말 맛 있다 스파게티 류 면류 없다 아쉽다 음식 맛 괜춘 무엇 분위기 좋다 위치 합정 이다 그 안 들어가다 멀리 근교 나오다 있다 듯 기분 느끼다 오다
직원 테이블 리을 도 주다 웨이팅 하다 보다 이름 불다 음료 맛있다 성비 좋다 것 같다 요 개인 매장 내 식물 많다 풀 냄새 나서다 좋다 담번 브런치 먹다 갈래
카페 인테리어 예쁘다 이름 걸 맞다 식물 많다 좋다 건물 외부 자리 만들다 어서 날 좋다 때 애 이용 하다 좋다 것 같다 요 브런치 메뉴 금액 대다 조금 높다 편이 매우 만족하다 첫 방문 이다
이제 서울 꽤 많다 포비 매장 생기다 역시 최고 포비 베이직 합정 매장 이다 통 유리 건물 통째 사용 있다 건물 외관 예쁘다
요기 빛 좋다 인테리어 이 쁘 참새 있다 참새 익숙하다 빵 얻어먹다 커피 맛있다 러스크 가격 좀 사악하다 정말 매우 흔하다 알다 그 맛 돈 주다 사 먹다 그 맛있다 맛 다른 지점 가보다
주말 저녁 가보다 평일 낮 방문 하다 좋다 그것 봄 여유 있다 정말 커피 말 하다 것 맛있다 피콜로 좋아하다 베이글 크림 치즈 없다 맛있다 것 구매 하다 수 있다
등반 후 먹다 흑임자 치즈케이크 이다 아이스 아메리카노 산 밉다 없다 고소하다 묵직하다 맛 나다 흑임자 치즈케이크 산 모양 겉 모습 하다 거 같다 촉촉하다 요 고소하다 요 치즈 자다 못 먹다 맛있다 자다 먹다 인기 진짜 많다 사람 많다 혹시 여유롭다 카페 작업 하다 가다 실 땐 평일 날 추천 드리다 주말 친구 수 떨다 오시 게 좋다 듯 하다
카페 이 쁘 감각 이다 말 차 파운드 못 먹다 얼 그레이 맛있다 토마토 바질 이드 기대하다 생각 다른 맛 이다 좋다 바질 좋아하다 진짜 괜찮다 토마토 맛 바질 향 진하다 느낌 깔끔하다 커피 산미 있다 타다 맛나 게 아니다 중간 좋다 퀸 주호 친절하다
강아지 산책 하다 때 지나가다 사람 많다 처음 생기다 때 사람 많다 않다 강아지 지나가다 들어오다 그렇다 이제 핫 플 되어다 버리다 평일 일찍 오픈 시간 오니 매장 사진 실컷 찍다 편안하다 커피타임 가지다 썸 커피 존 맛 뱅이 용 커피 디저트 분위기 가지다 핫 레이스
해리포터 마니아 라면 좋아하다 카페 이다 음료 비싸다 맛있다 구경 하다 재밌다
해리 포터 좋아하다 사람과 하다 더 좋다 곳 해리포터 음악 계속 나오다 좋다
홍대 어떻다 카페 갈다 친구 고민 하다 중 해리포터 카페 유명하다 선택 하다 되어다 저 다른 사람 다르다 않다 리뷰 검색 결정 하다 편 맛 대해 평가 좋다 편이 아니다 중간 조금 고민 되어다 직접 가보다 결과 저 무난 하다 맛 인테리어 매혹 되어다 입장료 내다 전시회 녀온 기분 이다 사진 찍다 것 좋아하다 분 평범하다 인테리어 조금 더 유니크 인테리어 좋아하다 분 강력하다 추천 드리다 진짜 친구 재밌다 다양하다 콘셉트 사진 찍다 볼 수 있다 좋다
칼 막 먹다 싶다 찾아가다 저녁 가다 품절 덥다 아쉽다 하다 카페 조용하다 좋다 커피 말다 오다 체증 베다 처음 접다 보다 생각 먹다 만 하다 말다 때 섞이다 들어오다 원두 가루 거부 감 들다 않다 그렇다 가다 홀짝 홀짝 자다 마시다 다음 좀 일찍 가다 칼 막 즐기다 려고 요
죤 맛 자다 먹다 토스트 더 굽다 달라 하다 걸 그렇다 더 바삭 게 좋다 골든 크림 라테 생각 라테 산미 느껴지다 제 취향 아니다 칼 막 자다 먹다
시원하다 쾌적하다 메뉴 신기 핸드 드립 커피 과 테 말르다 좋다 다음 터키 카이 막도 먹다 보다
갑자기 걷다 비 내다 들어오다 빗 소리 들다 맥주 하다 잔 말다 있다 좋다
플라워 카페 이 뻐 들어가다 때 꽃 향기도 좋다 층 있다 테라스 있다 바나나 주스 진짜 맛있다 딸기 케이크 조금 더 달다 좋다 굿굿
인절미 크루아상 존 맛 향기 나 꽃 둘러싸이다 디저트 먹다 기 분 전환 지대 하다
에스프레소 맛집 원두 기름 자다 어우러지다 신선하다 원두 갓 내리다 커피 초콜릿 더 맛있다 스프 레 소 좋아하다 분 추천 발견 커피 맛
케이크 정말 맛있다 녹차 시폰 데 녹차 크림 정말 진하다 맛있다 진짜 케이크 정말 강 추하다
음료 맛있다 케이크 귀엽다 셀카 찍기 좋다 예쁘다 곳
크다 로크 햄 치즈 치킨 퀘사디아 주문 하다 치킨 브리또 먹다 하다 품절 브리또 비슷하다 퀘사디아 추천 해주다 먹다 맛있다 요 감자 튀김 나오다 정말 배 부르다 맛있다 먹다
음식 맛있다 무엇 일찍 열다 저희 일찍 만나다 사람 딱이다
야외 테이블 자리 싱 그렇다 분위기 바람 시원하다 좋다 직원 친절하다 응대 자다 해주다 좋다 메뉴 성비 좋다 맛있다 친구 브런치 하다 편하다 여유 브런치
매장 넓다 음료 맛있다 색감 이 뻐 요 한라봉 이드 찌다 추천 자꾸 생각나다 맛 포토 존 사진 자다 나오다 사진 찍기
커피 맛있다 분위기 좋다 사진 찍 곳도 많다 직원 분 친절하다
훌륭훌 륭 날 덥다 이드 주문 하다 맛있다 직원 친절하다
갈다 때 만석 출판사 카페 볼거리 많다 답답하다 않다 분위기 편하다
분위기 히프 샌드위치 맛있다 레모네이드 양 많다 레몬이 가득 좋다
다양하다 메뉴 있다 또 책 옷 신발 굿즈 있다 신기하다 샌드위치 맛있다 착즙 주스 건강하다 맛있다 완전하다 만족
요기 오다 왜 사람 많다 지다 알다 진짜 디저트 따다 곳 볼 수 없다 메뉴 특별하다 곳 같다 용
느끼하다 않다 달 지도 않다 디저트 맛 집 이다 포장 예쁘다 선물 하다 좋다
디저트 가격 놀라다 저렴 들다 로만 구매 하다 커피 아이스 라테 사람 많다
매장 완전 분위기 있다 층 대화 하다 좋다 층 공부 하다 좋다 분위기 티 크림 첫 맛 좀 쓰다 말다 오틀리 밀크 올라오다 고소
힙 음악 여기 음악 개쩜 음악 일가 견 있다 여기 음악 히프 하다 걸 듣다 알 거임 힙 인테리어 정면 분할 스크린 개 힙합 음악 찰떡 어둑하다 은 하다 라이팅 끝내주다 분할 되다 공간 위층 음악 안 나오다 공부 하다 사람 계심 게다가 거 기다 테라스 있다 커피 티 크림 진짜 개존 맛 잔 끝판 다음 드립 커피 먹다 보다 겠다
드립 커피 말다 간혹 다니다 카페 요 저녁 시 정도 가다 드립 마감 아메리카노 말다 수 있다 최애 원두 윌리엄 블 레이크 어제 요건 선택 불가라 버터 팻 트리오 마시다 괜찮다 사진 설탕 왜 이 리 설탕 맛있다 합 정점 매장 넓다 크다 좌석 많다 좋다 것 같다 요 대화 하다 합 정점 추천 하다 망원 쪽 교점 대화 눈치 보이 어둡다 자다 안 가게 되다 합 정이 좋다
커피 맛있다 디저트 정말 맛있다 스콘 심플 하다 겉 바삭 속 부드럽다 계속 입 들어가다 얼그레이 가다 또 쇼콜라 진하다 크림 일 품 이다 살 안 찌다 매일 먹다 싶다
커피 맛있다 전문가 맛 원래 유명하다 곳 이다 빵 맛있다 다만 앞 주차 공간 넓다 않다 쉬다 않다 요
옥션 테이 스팅 코스 커피 내다 말다 얼마 안 돼다 이렇다 비싸다 커피 마시다 맛 느끼다 수 있다 걱정 돼다 바리스타 분 자세하다 설명 해주시 포인트 자다 잡다 만족스럽다
합정역 브런치 맛 집 깔끔하다 인테리어 모임 장소 추 천 주차 지원 가능 잠봉 뵈르 맛있다 그 인 헬 맛있다 봉골 레 다소 비리 특이하다 자꾸 당 김
인테리어 이 쁘 브런치 기 대다 이상 이다 이쁘다 나오다 기분 좋다 오다 타임 클래식 플래터 먹다 맛있다 다만 직원 바쁘다 보이다 담 또 들르다 싶다
음식 따뜻하다 자다 나오다 맛있다 후 무스 샐러드 처음 먹다 굳다 굳이 네 욤 저 라자냐 그 헬 굳다
야외 석 층 여유 배 불다 디저트 맛 집 디저트 못 먹기 용 망고 요건 추천 특별 하다 메뉴 다용
디저트 맛있다 외부 테이블 마시다 날씨 좋다 즐겁다
루프 탑 하다 수 있다 것 같다 일단 접근성 좋다 두 방문 맛 없다 케이크 모르다 크림 먹다 빵 맛 없다 성 앉다 싶다 오다 거 추천
밀크 티 머 스캣 양 나 고 좋다 좌석 편하다 테라스 캠핑 느낌 되어다 있다 아주 좋다
카페 아기자기하다
스콘 맛 지다
아메리칸 시계 브런치 좋다 곳 간단하다 하다 끼 먹기 좋다 평범하다 브렉 퍼스트 그리다 안성맞춤
브런치 맛있다 보 찾아가다 구성 비도 좋다 매장 자체 미국 느낌 낭랑하다
아침 여유롭다 먹다 융
햇빛 따스하다 외부 커피 한잔

In [300]:
df.head(3)

,cafe_name,quary,region,evaluation,rating,coffee_price,who
0,umoae,합정,서교동,인테리어 감각 느끼다 사장 친절하다 디저트 맛있다 소르베 재미있다,NaN,NaN,netizen
1,umoae,합정,서교동,커피 디저트 모두 맛있다 가게 분위기 원목 가구 써다 그렇다 단정하다 대화 하다 좋...,NaN,NaN,netizen
2,umoae,합정,서교동,프렌치 토스트 소문 존 맛,NaN,NaN,netizen

In [301]:
vectorize = TfidfVectorizer(min_df = 3, ngram_range = (1,3))

In [302]:
features = vectorize.fit_transform(df['evaluation'])
feature_vect_dense = features.todense()
# pd.DataFrame(feature_vect_dense, columns = vectorize.get_feature_names_out())

In [303]:
from sklearn.metrics.pairwise import cosine_similarity

In [304]:
cos_sim = cosine_similarity(features, features, dense_output=True)

In [305]:
pd.DataFrame(cos_sim)

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,54
0,1.000000,0.130984,0.0,0.248671,0.037371,0.106454,0.000000,0.222390,0.060890,0.025897,...,0.271657,0.209403,0.000000,0.000000,0.000000,0.0,0.000000,0.070580,0.000000,0.000000
1,0.130984,1.000000,0.0,0.086994,0.197624,0.283143,0.000000,0.208969,0.325778,0.159754,...,0.225029,0.221473,0.111385,0.174639,0.000000,0.0,0.419001,0.161016,0.000000,0.199021
2,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
3,0.248671,0.086994,0.0,1.000000,0.029494,0.071164,0.202981,0.201385,0.276578,0.073078,...,0.000000,0.023535,0.289354,0.188985,0.000000,0.0,0.070093,0.027852,0.000000,0.000000
4,0.037371,0.197624,0.0,0.029494,1.000000,0.402812,0.261552,0.144042,0.128861,0.297255,...,0.035108,0.266358,0.178447,0.116630,0.000000,0.0,0.420786,0.375563,0.198530,0.000000
5,0.106454,0.283143,0.0,0.071164,0.402812,1.000000,0.243610,0.136891,0.230340,0.259169,...,0.127875,0.240358,0.236868,0.157868,0.208949,0.0,0.471288,0.224034,0.000000,0.247893
6,0.000000,0.000000,0.0,0.202981,0.261552,0.243610,1.000000,0.064332,0.090832,0.147380,...,0.000000,0.000000,0.055259,0.076129,0.000000,0.0,0.000000,0.360085,0.000000,0.000000
7,0.222390,0.208969,0.0,0.201385,0.144042,0.136891,0.064332,1.000000,0.375500,0.218250,...,0.000000,0.117965,0.114597,0.129411,0.000000,0.0,0.117111,0.139605,0.229106,0.115038
8,0.060890,0.325778,0.0,0.276578,0.128861,0.230340,0.090832,0.375500,1.000000,0.321376,...,0.207083,0.083279,0.408308,0.135209,0.000000,0.0,0.223562,0.098555,0.000000,0.081212
9,0.025897,0.159754,0.0,0.073078,0.297255,0.259169,0.147380,0.218250,0.321376,1.000000,...,0.135291,0.047224,0.350693,0.040410,0.160457,0.0,0.190161,0.055887,0.412724,0.000000
10,0.156455,0.194982,0.0,0.180966,0.127400,0.221772,0.172168,0.306176,0.195413,0.243742,...,0.000000,0.089096,0.104998,0.270984,0.201817,0.0,0.176901,0.274740,0.173037,0.086884
11,0.067492,0.331788,0.0,0.030857,0.138017,0.080802,0.239094,0.061951,0.146632,0.344956,...,0.136874,0.061538,0.017292,0.101013,0.000000,0.0,0.041458,0.091550,0.000000,0.143386
12,0.057908,0.108068,0.0,0.053646,0.211097,0.178977,0.109854,0.076361,0.238745,0.212460,...,0.054402,0.052800,0.037258,0.000000,0.358803,0.0,0.089324,0.062485,0.000000,0.000000
13,0.000000,0.382230,0.0,0.116349,0.167777,0.312036,0.000000,0.075395,0.327523,0.122423,...,0.053714,0.104264,0.101547,0.178440,0.000000,0.0,0.398722,0.123390,0.000000,0.000000
14,0.164416,0.180659,0.0,0.146378,0.084751,0.331347,0.058833,0.262706,0.250836,0.287725,...,0.107010,0.031660,0.111101,0.274939,0.215143,0.0,0.201411,0.037467,0.000000,0.000000
15,0.000000,0.225701,0.0,0.041672,0.153347,0.088220,0.000000,0.093349,0.147164,0.344073,...,0.041308,0.105126,0.186910,0.034306,0.136219,0.0,0.127525,0.023723,0.233587,0.058644
16,0.000000,0.217923,0.0,0.016614,0.164244,0.089778,0.000000,0.130245,0.148247,0.437901,...,0.039553,0.038388,0.214232,0.065698,0.000000,0.0,0.179273,0.045430,0.447330,0.000000
17,0.000000,0.183241,0.0,0.019518,0.228617,0.164457,0.000000,0.149809,0.063262,0.128025,...,0.141082,0.045096,0.079718,0.077179,0.000000,0.0,0.134310,0.053369,0.262751,0.131931
18,0.000000,0.163080,0.0,0.179438,0.097176,0.115653,0.080905,0.101770,0.204484,0.094656,...,0.050952,0.049452,0.122312,0.162748,0.000000,0.0,0.230940,0.058523,0.000000,0.000000
19,0.042190,0.168436,0.0,0.359366,0.120522,0.289908,0.125871,0.213967,0.223553,0.144785,...,0.000000,0.115404,0.237416,0.411767,0.261410,0.0,0.229137,0.136574,0.000000,0.000000
20,0.274018,0.297688,0.0,0.000000,0.185915,0.063913,0.000000,0.132813,0.173104,0.386497,...,0.555712,0.249847,0.184288,0.000000,0.000000,0.0,0.168320,0.000000,0.579700,0.000000
21,0.042440,0.193444,0.0,0.000000,0.024247,0.000000,0.000000,0.153787,0.176706,0.156308,...,0.102106,0.038696,0.069927,0.000000,0.000000,0.0,0.000000,0.045794,0.000000,0.226414
22,0.064366,0.036710,0.0,0.131422,0.036774,0.000000,0.000000,0.304454,0.262219,0.065705,...,0.000000,0.058688,0.212254,0.000000,0.000000,0.0,0.000000,0.069453,0.000000,0.000000
23,0.057842,0.131957,0.0,0.022826,0.398597,0.216038,0.198388,0.114410,0.080769,0.045801,...,0.000000,0.105480,0.171796,0.090260,0.000000,0.0,0.157074,0.124828,0.000000,0.000000
24,0.077345,0.144342,0.0,0.100816,0.216755,0.045302,0.000000,0.439375,0.343499,0.572653,...,0.165706,0.070523,0.234775,0.000000,0.000000,0.0,0.119306,0.083459,0.616342,0.000000
25,0.048125,0.027447,0.0,0.091481,0.027496,0.000000,0.000000,0.063460,0.044800,0.079201,...,0.000000,0.043880,0.000000,0.000000,0.000000,0.0,0.000000,0.051929,0.000000,0.000000
26,0.148633,0.335045,0.0,0.072158,0.407853,0.317453,0.000000,0.102008,0.190479,0.215842,...,0.240595,0.248761,0.072481,0.261153,0.000000,0.0,0.565071,0.344358,0.000000,0.000000
27,0.037374,0.021315,0.0,0.046557,0.282245,0.000000,0.190674,0.049283,0.034792,0.137649,...,0.089917,0.034077,0.061580,0.000000,0.000000,0.0,0.000000,0.167632,0.000000,0.000000
28,0.226272,0.279555,0.0,0.072672,0.246286,0.129874,0.089363,0.279290,0.104105,0.124866,...,0.000000,0.085902,0.026678,0.073508,0.000000,0.0,0.127921,0.101660,0.000000,0.125655
29,0.279078,0.108427,0.0,0.000000,0.197158,0.034030,0.000000,0.076614,0.146254,0.101400,...,0.054583,0.052975,0.037381,0.000000,0.000000,0.0,0.089620,0.062693,0.000000,0.000000
30,0.000000,0.223014,0.0,0.074006,0.086458,0.161472,0.122284,0.000000,0.000000,0.183911,...,0.000000,0.000000,0.000000,0.242266,0.399400,0.0,0.000000,0.000000,0.000000,0.000000
31,0.094939,0.374120,0.0,0.146463,0.290062,0.261748,0.180102,0.187786,0.132569,0.251655,...,0.000000,0.173128,0.053767,0.148147,0.000000,0.0,0.257811,0.204886,0.000000,0.000000
32,0.132809,0.075746,0.0,0.386989,0.075879,0.118094,0.198115,0.336774,0.351863,0.052581,...,0.189419,0.121094,0.138847,0.191286,0.000000,0.0,0.000000,0.143307,0.000000,0.000000
33,0.117407,0.066961,0.0,0.140346,0.154852,0.222884,0.088695,0.000000,0.082770,0.416601,...,0.327546,0.107051,0.393463,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
34,0.122882,0.489696,0.0,0.064643,0.087678,0.357681,0.260667,0.032264,0.178971,0.130885,...,0.249206,0.156660,0.059197,0.076360,0.000000,0.0,0.208366,0.052802,0.000000,0.000000
35,0.143748,0.270302,0.0,0.000000,0.113934,0.102813,0.108594,0.065973,0.137383,0.351389,...,0.291523,0.131068,0.036830,0.000000,0.000000,0.0,0.088300,0.000000,0.000000,0.152696
36,0.000000,0.643644,0.0,0.205814,0.184810,0.268331,0.226201,0.086993,0.360304,0.119747,...,0.064459,0.062560,0.180201,0.156479,0.000000,0.0,0.292158,0.190893,0.000000,0.000000
37,0.099572,0.248408,0.0,0.223114,0.171177,0.106760,0.094105,0.253528,0.356195,0.275689,...,0.088899,0.000000,0.216202,0.209410,0.000000,0.0,0.145964,0.000000,0.167568,0.168277
38,0.022861,0.384523,0.0,0.084657,0.274850,0.252198,0.194105,0.114464,0.224239,0.298859,...,0.097956,0.151006,0.161540,0.104275,0.141650,0.0,0.194689,0.151876,0.000000,0.060982
39,0.176846,0.229826,0.0,0.164197,0.111586,0.070408,0.074368,0.395142,0.287612,0.272204,...,0.199642,0.161246,0.230522,0.000000,0.000000,0.0,0.060470,0.084601,0.208259,0.104570
40,0.093726,0.315638,0.0,0.043414,0.053549,0.056720,0.088901,0.308743,0.125378,0.080664,...,0.000000,0.085458,0.000000,0.000000,0.000000,0.0,0.000000,0.101134,0.000000,0.125005
41,0.227922,0.188683,0.0,0.317756,0.000000,0.000000,0.070582,0.166651,0.158304,0.101032,...,0.000000,0.183112,0.049467,0.068149,0.000000,0.0,0.000000,0.000000,0.000000,0.252427
42,0.410670,0.090840,0.0,0.000000,0.234630,0.259221,0.000000,0.375779,0.148271,0.063059,...,0.000000,0.145225,0.000000,0.000000,0.000000,0.0,0.341340,0.443131,0.000000,0.000000
43,0.175782,0.096474,0.0,0.332782,0.285245,0.254239,0.080222,0.341471,0.059050,0.236572,...,0.000000,0.077116,0.260899,0.065989,0.000000,0.0,0.296091,0.235307,0.224655,0.000000
44,0.059731,0.034066,0.0,0.187949,0.097123,0.000000,0.000000,0.151463,0.055604,0.282154,...,0.000000,0.054462,0.062446,0.000000,0.000000,0.0,0.000000,0.064452,0.317318,0.000000
45,0.271657,0.225029,0.0,0.000000,0.035108,0.127875,0.000000,0.000000,0.207083,0.135291,...,1.000000,0.247694,0.123924,0.000000,0.000000,0.0,0.083435,0.000000,0.000000,0.000000
46,0.209403,0.221473,0.0,0.023535,0.266358,0.240358,0.000000,0.117965,0.083279,0.047224,...,0.247694,1.000000,0.033776,0.093065,0.000000,0.0,0.161954,0.128707,0.000000,0.438405
47,0.000000,0.111385,0.0,0.289354,0.178447,0.236868,0.055259,0.114597,0.408308,0.350693,...,0.123924,0.033776,1.000000,0.111159,0.000000,0.0,0.157735,0.039972,0.196793,0.000000
48,0.000000,0.174639,0.0,0.188985,0.116630,0.157868,0.076129,0.129411,0.135209,0.040410,...,0.000000,0.093065,0.111159,1.000000,0.000000,0.0,0.277172,0.375401,0.000000,0.000000
49,0.000000,0.000000,0.0,0.000000,0.000000,0.208949,0.000000,0.000000,0.000000,0.160457,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.0,0.000000,0.000000,0.000000,0.000000
50,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
51,0.000000,0.419001,0.0,0.070093,0.420786,0.471288,0.000000,0.117111,0.223562,0.190161,...,0.083435,0.161954,0.157735,0.277172,0.000000,0.0,1.000000,0.494179,0.000000,0.000000
52,0.070580,0.161016,0.0,0.027852,0.375563,0.224034,0.360085,0.139605,0.098555,0.055887,...,0.000000,0.128707,0.039972,0.375401,0.000000,0.0,0.494179,1.000000,0.000000,0.000000
53,0.000000,0.000000,0.0,0.000000,0.198530,0.000000,0.000000,0.229106,0.000000,0.412724,...,0.000000,0.000000,0.196793,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000
54,0.000000,0.199021,0.0,0.000000,0.000000,0.247893,0.000000,0.115038,0.081212,0.000000,...,0.000000,0.438405,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,1.000000

In [306]:
index = pd.DataFrame(cos_sim)[54].sort_values(ascending = False)[:11].index

In [307]:
df['evaluation'].iloc[index]

54                                     햇빛 따스하다 외부 커피 한잔
46                         디저트 맛있다 외부 테이블 마시다 날씨 좋다 즐겁다
41    옥션 테이 스팅 코스 커피 내다 말다 얼마 안 돼다 이렇다 비싸다 커피 마시다 맛 ...
5     카페 인테리어 예쁘다 이름 걸 맞다 식물 많다 좋다 건물 외부 자리 만들다 어서 날...
21    에스프레소 맛집 원두 기름 자다 어우러지다 신선하다 원두 갓 내리다 커피 초콜릿 더...
1     커피 디저트 모두 맛있다 가게 분위기 원목 가구 써다 그렇다 단정하다 대화 하다 좋...
37    힙 음악 여기 음악 개쩜 음악 일가 견 있다 여기 음악 히프 하다 걸 듣다 알 거임...
35            디저트 가격 놀라다 저렴 들다 로만 구매 하다 커피 아이스 라테 사람 많다
11    강아지 산책 하다 때 지나가다 사람 많다 처음 생기다 때 사람 많다 않다 강아지 지...
17    시원하다 쾌적하다 메뉴 신기 핸드 드립 커피 과 테 말르다 좋다 다음 터키 카이 막...
28                   커피 맛있다 분위기 좋다 사진 찍 곳도 많다 직원 분 친절하다
Name: evaluation, dtype: object

외부이라는 단어가 부정적일때 어떻게 처리해야하는가?

In [308]:
similarity_simple_pair = cosine_similarity(features[54] , features)
print(similarity_simple_pair)

[[0.         0.19902117 0.         0.         0.         0.2478933
  0.         0.11503755 0.08121169 0.         0.08688439 0.14338644
  0.         0.         0.         0.05864385 0.         0.13193135
  0.         0.         0.         0.22641424 0.         0.
  0.         0.         0.         0.         0.12565542 0.
  0.         0.         0.         0.         0.         0.15269649
  0.         0.16827738 0.06098155 0.10457015 0.12500522 0.25242716
  0.         0.         0.         0.         0.43840488 0.
  0.         0.         0.         0.         0.         0.
  1.        ]]

In [255]:
df['evaluation'][46]

'디저트 맛있어요?? 외부 테이블에서 마셨는데 날씨도 좋구 즐거웠어요??'

In [ ]:
df['evaluation'][41]

'옥션 테이 스팅 코스 커피 내다 말다 얼마 안 돼다 이렇다 비싸다 커피 마시다 맛 느끼다 수 있다 걱정 돼다 바리스타 분 자세하다 설명 해주시 포인트 자다 잡다 만족스럽다'

In [ ]:
df['evaluation'][54]

'햇빛 따스하다 외부 커피 한잔'

# 유사도 비교한 문장들의 카페 이름 1~5순위까지 보여주기

In [309]:
# 유사도 높은 순으로 정렬하기
(-similarity_simple_pair).argsort()

array([[54, 46, 41,  5, 21,  1, 37, 35, 11, 17, 28, 40,  7, 39, 10,  8,
        38, 15, 43, 42, 33, 45, 47, 48, 49, 50, 36, 51, 52, 34, 44, 32,
         0, 30,  2,  3,  4,  6,  9, 12, 13, 14, 16, 18, 19, 20, 22, 23,
        24, 25, 26, 53, 29, 31, 27]])

In [312]:
df.head()

,cafe_name,quary,region,evaluation,rating,coffee_price,who
0,umoae,합정,서교동,인테리어 감각 느끼다 사장 친절하다 디저트 맛있다 소르베 재미있다,NaN,NaN,netizen
1,umoae,합정,서교동,커피 디저트 모두 맛있다 가게 분위기 원목 가구 써다 그렇다 단정하다 대화 하다 좋...,NaN,NaN,netizen
2,umoae,합정,서교동,프렌치 토스트 소문 존 맛,NaN,NaN,netizen
3,어반플랜트 합정,합정,합정동,자연 둘러싸이다 있다 듯 색다르다 기분 느끼다 수 있다 처 오믈렛 정말 맛 있다 스...,NaN,NaN,netizen
4,어반플랜트 합정,합정,합정동,직원 테이블 리을 도 주다 웨이팅 하다 보다 이름 불다 음료 맛있다 성비 좋다 것 ...,NaN,NaN,netizen

In [336]:
index = (-similarity_simple_pair).argsort()
print('{}님, 검색 문장 : "{}" 에 대한 카페 추천 시스템의 결과입니다\n'.format(df['who'][54], df['evaluation'][54]))
for i in range(1,6):
    order = index[0][i]
    print('당신을 위한 추천 카페는 "{}"'.format(df['cafe_name'][order]))

eden님, 검색 문장 : "햇빛 따스하다 외부 커피 한잔" 에 대한 카페 추천 시스템의 결과입니다

당신을 위한 추천 카페는 "허밍벨라"
당신을 위한 추천 카페는 "빈브라더스 합정"
당신을 위한 추천 카페는 "어반플랜트 합정"
당신을 위한 추천 카페는 "차곡파티세리"
당신을 위한 추천 카페는 "umoae"

# 결과를 어떻게 하면 보여줄 수 있을까?