In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/edenLee94/caffeine-meeting/main/cafe_seoul.csv')
df

,cafe_name,quary,region,evaluation,rating,coffee_price
0,umoae,합정,서교동,인테리어가 감각적이라고 느꼈습니다 사장님이 친절하시고 디저트가 맛있어요 소르베도 재...,NaN,NaN
1,umoae,합정,서교동,커피와 디저트 모두 너무 맛있어요 가게 분위기도 원목 가구를 써서 그런지 단정하고 ...,NaN,NaN
2,umoae,합정,서교동,프렌치토스트 소문대로 존맛탱,NaN,NaN
3,어반플랜트 합정,합정,합정동,자연에 둘러쌓여 있는듯한 색다른 기분도 느낄수있었고~ 시그니처 오믈렛 정말 맛있었어...,NaN,NaN
4,어반플랜트 합정,합정,합정동,직원분이 테이블링을 도와주셔서 웨이팅을 하다보면 이름을 불러주세요~ 음료도 맛있었고...,NaN,NaN
5,어반플랜트 합정,합정,합정동,카페 인테리어도 예쁘고 이름에 걸맞게 식물들이 많아서 좋았습니다. 특히 건물 외부에...,NaN,NaN
6,포비 베이직,합정,합정동,이제 서울에 꽤나 많은 포비 매장이 생겼지만 역시나 최고는 포비 베이직 합정 매장입...,NaN,NaN
7,포비 베이직,합정,합정동,요기 빛도 너무 좋구 인테리어도 이쁘구 참새도 있음!!! 참새 너무 익숙하게 빵 얻...,NaN,NaN
8,포비 베이직,합정,합정동,주말이나 저녁에 가보다가 평일 낮에 방문하니 너무 좋더라구요! 그것도 봄!! 여유 ...,NaN,NaN
9,어썸마운틴,합정,동교동,500m에서 등반 후 먹는 흑임자치즈케이크와 아아 입니다 아이스아메리카노가 산미 없...,NaN,NaN
10,어썸마운틴,합정,동교동,카페가 이쁘고 감각적입니다! 말차파운드는 못먹었지만 얼그레이도 맛있었어요! 토마토바...,NaN,NaN
11,어썸마운틴,합정,동교동,맨날 강아지랑 산책할때마다 지나가는데 사람이 엄청 많습니다 처음에 생겼을때는 사람이...,NaN,NaN
12,943 킹스크로스CAFE,합정,서교동,해리포터 매니아라면 너무나 좋아할 카페입니다 음료도 비싸지만 맛있고 구경하기 재밌어요~,NaN,NaN
13,944 킹스크로스CAFE,합정,서교동,해리포터를 좋아하는 사람과 함께하면 더 좋은 곳!! 해리포터 음악이 계속 나와서 좋...,NaN,NaN
14,945 킹스크로스CAFE,합정,서교동,홍대에서 어떤 카페를 갈까 친구들과 고민을 하던 중 해리포터 카페로 유명해서 선택하...,NaN,NaN
15,샌드커피 논탄토 연남,합정,동교동,카이막이 먹고 싶어서 찾아갔는데ㅠㅠ 저녁에 갔더니 품절이더라구요!! 아쉽긴 했지만 ...,NaN,NaN
16,샌드커피 논탄토 연남,합정,동교동,죤맛 너무 잘 먹었어요 토스트는 더 구워 달라고 할 걸 그랬어요! 더 바삭한게 좋아...,NaN,NaN
17,샌드커피 논탄토 연남,합정,동교동,시원하고 쾌적하고 메뉴 신기 핸드드립 커피 과테말라 좋아요 다음엔 터키식 카이막도 ...,NaN,NaN
18,콜린,합정,서교동,갑자기 걷는데 비가내려서 들어왔어요. 빗소리 들으면서 맥주 한잔 마시고 있는데 넘나...,NaN,NaN
19,콜린,합정,서교동,플라워카페 너무 이뻐요 들어갈때 꽃향기도 좋고 2층도 있고 테라스도 있고 바나나주스...,NaN,NaN
20,콜린,합정,서교동,인절미 크루아상 대존맛탱구리구리ㅜㅜ 향기나는 꽃들에 둘러쌓여 디저트 먹으면서 기분전...,NaN,NaN
21,차곡파티세리,합정,서교동,에스프레소 맛집 원두 기름이 잘 어우러지는 신선한 원두로 갓내린 커피 초콜릿은 더 ...,NaN,NaN
22,차곡파티세리,합정,서교동,케이크가 정말 너무 맛있어요!!! 녹차쉬폰인데 녹차 크림이 정말 진하고 맛있더라구요...,NaN,NaN
23,차곡파티세리,합정,서교동,음료도 맛있구 케이크가 넘 귀여워요~~셀카찍기 좋은 예쁜 곳^^,NaN,NaN
24,브런치가,합정,동교동,크로크햄 치즈와 치킨퀘사디아를 주문했습니다. 치킨 브리또를 먹으려고 했지만 품절이라...,NaN,NaN
25,브런치가,합정,동교동,"음식도 맛있고, 무엇보다 일찍 열어서 저희처럼 일찍 만나는 사람에게 딱이였어요~^^",NaN,NaN
26,브런치가,합정,동교동,야외 테이블 자리마다 싱그러운 분위기. 바람 시원하고 좋아요.직원 분들 친절하시고 ...,NaN,NaN
27,랑데자뷰 홍대점,합정,서교동,매장도 넓고 음료도 맛있어요! 색감이 되게 이뻐 요 ㅎㅎ 특히 한라봉에이드 찐 추천...,NaN,NaN
28,랑데자뷰 홍대점,합정,서교동,커피도 맛있고 분위기도 좋아요 사진찍을 곳도 많고 직원분들이 친절해용>_<,NaN,NaN
29,랑데자뷰 홍대점,합정,서교동,"훌륭훌륭???????? 날이 더워서 에이드 주문했는데 넘 맛있구, 직원들도 친절해요 ??",NaN,NaN
30,1984,합정,동교동,갈 때마다 만석인 1984 출판사 카페♡ 볼거리도 많고 답답하지 않은 분위기라 편해요!,NaN,NaN
31,1984,합정,동교동,분위기도 힙하고 샌드위치가 맛있네요 레몬에이드는 양 많고 레몬이 가득이라 좋았어요,NaN,NaN
32,1984,합정,동교동,다양한 메뉴가 있고 또 책이나 옷 신발 굿즈까지 있 어서 너무 신기해요 샌드위치 너...,NaN,NaN
33,얀 쿠브레,합정,동교동,요기 첨왔는데 왜 사람이 많은지 알겠네요 진짜 디저트도 딴곳에서 볼수없는 메뉴들이랑...,NaN,NaN
34,얀 쿠브레,합정,동교동,느끼하지도 않고 너무 달지도 않은 디저트 맛집입니다. 포장이 예뻐서 선물하기도 좋습니다.,NaN,NaN
35,얀 쿠브레,합정,동교동,디져트 가격에 놀래서... 저렴이 들로만 구매 했어요~ 커피는 아이스라떼로~ 사람 ...,NaN,NaN
36,앤트러사이트 합정점,합정,합정동,매장이 완전 분위기 있어요~ 1층은 대화하기 좋고 2 층은 공부하기 좋은 분위기네요...,NaN,NaN
37,앤트러사이트 합정점,합정,합정동,1. 힙한 음악 여기 음악 개쩜. 음악 일가견 있다면 여기 음악들 힙하다는걸 듣자마...,NaN,NaN
38,앤트러사이트 합정점,합정,합정동,드립커피 마시러 간혹 다니는 카페에요! 저녁 9시 정도에 가서 이미 드립은 마감이라...,NaN,NaN
39,빈브라더스 합정,합정,합정동,커피도 다 맛있고 디저트도 정말 맛있어요. 특히 스콘이 심플하면서도 겉은 바삭하고 ...,NaN,NaN
40,빈브라더스 합정,합정,합정동,"커피 맛있어요~ 전문가의 맛이죠~ 원래 유명한 곳이었구요~ 빵도 맛있구요~ 다만, ...",NaN,NaN
41,빈브라더스 합정,합정,합정동,옥션 테이스팅 코스) 커피를 내려마신지 얼마 안돼서 이런 비싼 커피를 마셔도 맛을 ...,NaN,NaN
42,리피 메세나폴리스점,합정,서교동,"합정역 브런치맛집, 깔끔한인테리어, 모임장소로 추 천 주차지원가능 잠봉뵈르 맛있음,...",NaN,NaN
43,리피 메세나폴리스점,합정,서교동,인테리어도 이쁘고 브런치도 기대이상이었어요! 넘 이쁘게 나와서 기분좋고~ 올타임 클...,NaN,NaN
44,리피 메세나폴리스점,합정,서교동,음식 따뜻하게 잘나왔구 다 맛있었어용!!!!! 후무스샐러드처음먹는데 굳굳이네욤! 저...,NaN,NaN
45,허밍벨라,합정,서교동,"야외석부터 1,2층여유롭고 배가불러ㅜ디저트맛집 디저트못먹규가용 ㅜㅜ 망코!! 요건 ...",NaN,NaN
46,허밍벨라,합정,서교동,디저트 맛있어요?? 외부 테이블에서 마셨는데 날씨도 좋구 즐거웠어요??,NaN,NaN
47,허밍벨라,합정,서교동,루프탑? 이라고 할 수 있을 것 같음 일단 접근성이 좋고 두번째 방문인데 맛은 없음...,NaN,NaN
48,마가렛리버,합정,합정동,밀크티 머스캣향나고 넘 좋았어용 좌석도 편하고 테라스 캠핑느낌으로 되어있어서 아주 ...,NaN,NaN
49,마가렛리버,합정,합정동,카페가 아기자기해요ㅋㅋ,NaN,NaN
50,마가렛리버,합정,합정동,스콘맛집이어요??,NaN,NaN
51,트래블메이커,합정,동교동,아메리칸식 브런치로 딱 좋은 곳!! 간단히 한 끼 먹기 좋습니다~^^ 평범한 블랙퍼...,NaN,NaN
52,트래블메이커,합정,동교동,브런치가 맛있어 보여서 찾아갔는데 가성비도 좋고 매장 자체부터 미국 느낌 낭낭해요~,NaN,NaN
53,트래블메이커,합정,동교동,아침에 여유롭게 먹다가융????,NaN,NaN
54,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df['who'] = 'netizen'
df
# 나중에 검색 결과 때문에 who라는 속성을 만들어주었다.

,cafe_name,quary,region,evaluation,rating,coffee_price,who
0,umoae,합정,서교동,인테리어가 감각적이라고 느꼈습니다 사장님이 친절하시고 디저트가 맛있어요 소르베도 재...,NaN,NaN,netizen
1,umoae,합정,서교동,커피와 디저트 모두 너무 맛있어요 가게 분위기도 원목 가구를 써서 그런지 단정하고 ...,NaN,NaN,netizen
2,umoae,합정,서교동,프렌치토스트 소문대로 존맛탱,NaN,NaN,netizen
3,어반플랜트 합정,합정,합정동,자연에 둘러쌓여 있는듯한 색다른 기분도 느낄수있었고~ 시그니처 오믈렛 정말 맛있었어...,NaN,NaN,netizen
4,어반플랜트 합정,합정,합정동,직원분이 테이블링을 도와주셔서 웨이팅을 하다보면 이름을 불러주세요~ 음료도 맛있었고...,NaN,NaN,netizen
5,어반플랜트 합정,합정,합정동,카페 인테리어도 예쁘고 이름에 걸맞게 식물들이 많아서 좋았습니다. 특히 건물 외부에...,NaN,NaN,netizen
6,포비 베이직,합정,합정동,이제 서울에 꽤나 많은 포비 매장이 생겼지만 역시나 최고는 포비 베이직 합정 매장입...,NaN,NaN,netizen
7,포비 베이직,합정,합정동,요기 빛도 너무 좋구 인테리어도 이쁘구 참새도 있음!!! 참새 너무 익숙하게 빵 얻...,NaN,NaN,netizen
8,포비 베이직,합정,합정동,주말이나 저녁에 가보다가 평일 낮에 방문하니 너무 좋더라구요! 그것도 봄!! 여유 ...,NaN,NaN,netizen
9,어썸마운틴,합정,동교동,500m에서 등반 후 먹는 흑임자치즈케이크와 아아 입니다 아이스아메리카노가 산미 없...,NaN,NaN,netizen
10,어썸마운틴,합정,동교동,카페가 이쁘고 감각적입니다! 말차파운드는 못먹었지만 얼그레이도 맛있었어요! 토마토바...,NaN,NaN,netizen
11,어썸마운틴,합정,동교동,맨날 강아지랑 산책할때마다 지나가는데 사람이 엄청 많습니다 처음에 생겼을때는 사람이...,NaN,NaN,netizen
12,943 킹스크로스CAFE,합정,서교동,해리포터 매니아라면 너무나 좋아할 카페입니다 음료도 비싸지만 맛있고 구경하기 재밌어요~,NaN,NaN,netizen
13,944 킹스크로스CAFE,합정,서교동,해리포터를 좋아하는 사람과 함께하면 더 좋은 곳!! 해리포터 음악이 계속 나와서 좋...,NaN,NaN,netizen
14,945 킹스크로스CAFE,합정,서교동,홍대에서 어떤 카페를 갈까 친구들과 고민을 하던 중 해리포터 카페로 유명해서 선택하...,NaN,NaN,netizen
15,샌드커피 논탄토 연남,합정,동교동,카이막이 먹고 싶어서 찾아갔는데ㅠㅠ 저녁에 갔더니 품절이더라구요!! 아쉽긴 했지만 ...,NaN,NaN,netizen
16,샌드커피 논탄토 연남,합정,동교동,죤맛 너무 잘 먹었어요 토스트는 더 구워 달라고 할 걸 그랬어요! 더 바삭한게 좋아...,NaN,NaN,netizen
17,샌드커피 논탄토 연남,합정,동교동,시원하고 쾌적하고 메뉴 신기 핸드드립 커피 과테말라 좋아요 다음엔 터키식 카이막도 ...,NaN,NaN,netizen
18,콜린,합정,서교동,갑자기 걷는데 비가내려서 들어왔어요. 빗소리 들으면서 맥주 한잔 마시고 있는데 넘나...,NaN,NaN,netizen
19,콜린,합정,서교동,플라워카페 너무 이뻐요 들어갈때 꽃향기도 좋고 2층도 있고 테라스도 있고 바나나주스...,NaN,NaN,netizen
20,콜린,합정,서교동,인절미 크루아상 대존맛탱구리구리ㅜㅜ 향기나는 꽃들에 둘러쌓여 디저트 먹으면서 기분전...,NaN,NaN,netizen
21,차곡파티세리,합정,서교동,에스프레소 맛집 원두 기름이 잘 어우러지는 신선한 원두로 갓내린 커피 초콜릿은 더 ...,NaN,NaN,netizen
22,차곡파티세리,합정,서교동,케이크가 정말 너무 맛있어요!!! 녹차쉬폰인데 녹차 크림이 정말 진하고 맛있더라구요...,NaN,NaN,netizen
23,차곡파티세리,합정,서교동,음료도 맛있구 케이크가 넘 귀여워요~~셀카찍기 좋은 예쁜 곳^^,NaN,NaN,netizen
24,브런치가,합정,동교동,크로크햄 치즈와 치킨퀘사디아를 주문했습니다. 치킨 브리또를 먹으려고 했지만 품절이라...,NaN,NaN,netizen
25,브런치가,합정,동교동,"음식도 맛있고, 무엇보다 일찍 열어서 저희처럼 일찍 만나는 사람에게 딱이였어요~^^",NaN,NaN,netizen
26,브런치가,합정,동교동,야외 테이블 자리마다 싱그러운 분위기. 바람 시원하고 좋아요.직원 분들 친절하시고 ...,NaN,NaN,netizen
27,랑데자뷰 홍대점,합정,서교동,매장도 넓고 음료도 맛있어요! 색감이 되게 이뻐 요 ㅎㅎ 특히 한라봉에이드 찐 추천...,NaN,NaN,netizen
28,랑데자뷰 홍대점,합정,서교동,커피도 맛있고 분위기도 좋아요 사진찍을 곳도 많고 직원분들이 친절해용>_<,NaN,NaN,netizen
29,랑데자뷰 홍대점,합정,서교동,"훌륭훌륭???????? 날이 더워서 에이드 주문했는데 넘 맛있구, 직원들도 친절해요 ??",NaN,NaN,netizen
30,1984,합정,동교동,갈 때마다 만석인 1984 출판사 카페♡ 볼거리도 많고 답답하지 않은 분위기라 편해요!,NaN,NaN,netizen
31,1984,합정,동교동,분위기도 힙하고 샌드위치가 맛있네요 레몬에이드는 양 많고 레몬이 가득이라 좋았어요,NaN,NaN,netizen
32,1984,합정,동교동,다양한 메뉴가 있고 또 책이나 옷 신발 굿즈까지 있 어서 너무 신기해요 샌드위치 너...,NaN,NaN,netizen
33,얀 쿠브레,합정,동교동,요기 첨왔는데 왜 사람이 많은지 알겠네요 진짜 디저트도 딴곳에서 볼수없는 메뉴들이랑...,NaN,NaN,netizen
34,얀 쿠브레,합정,동교동,느끼하지도 않고 너무 달지도 않은 디저트 맛집입니다. 포장이 예뻐서 선물하기도 좋습니다.,NaN,NaN,netizen
35,얀 쿠브레,합정,동교동,디져트 가격에 놀래서... 저렴이 들로만 구매 했어요~ 커피는 아이스라떼로~ 사람 ...,NaN,NaN,netizen
36,앤트러사이트 합정점,합정,합정동,매장이 완전 분위기 있어요~ 1층은 대화하기 좋고 2 층은 공부하기 좋은 분위기네요...,NaN,NaN,netizen
37,앤트러사이트 합정점,합정,합정동,1. 힙한 음악 여기 음악 개쩜. 음악 일가견 있다면 여기 음악들 힙하다는걸 듣자마...,NaN,NaN,netizen
38,앤트러사이트 합정점,합정,합정동,드립커피 마시러 간혹 다니는 카페에요! 저녁 9시 정도에 가서 이미 드립은 마감이라...,NaN,NaN,netizen
39,빈브라더스 합정,합정,합정동,커피도 다 맛있고 디저트도 정말 맛있어요. 특히 스콘이 심플하면서도 겉은 바삭하고 ...,NaN,NaN,netizen
40,빈브라더스 합정,합정,합정동,"커피 맛있어요~ 전문가의 맛이죠~ 원래 유명한 곳이었구요~ 빵도 맛있구요~ 다만, ...",NaN,NaN,netizen
41,빈브라더스 합정,합정,합정동,옥션 테이스팅 코스) 커피를 내려마신지 얼마 안돼서 이런 비싼 커피를 마셔도 맛을 ...,NaN,NaN,netizen
42,리피 메세나폴리스점,합정,서교동,"합정역 브런치맛집, 깔끔한인테리어, 모임장소로 추 천 주차지원가능 잠봉뵈르 맛있음,...",NaN,NaN,netizen
43,리피 메세나폴리스점,합정,서교동,인테리어도 이쁘고 브런치도 기대이상이었어요! 넘 이쁘게 나와서 기분좋고~ 올타임 클...,NaN,NaN,netizen
44,리피 메세나폴리스점,합정,서교동,음식 따뜻하게 잘나왔구 다 맛있었어용!!!!! 후무스샐러드처음먹는데 굳굳이네욤! 저...,NaN,NaN,netizen
45,허밍벨라,합정,서교동,"야외석부터 1,2층여유롭고 배가불러ㅜ디저트맛집 디저트못먹규가용 ㅜㅜ 망코!! 요건 ...",NaN,NaN,netizen
46,허밍벨라,합정,서교동,디저트 맛있어요?? 외부 테이블에서 마셨는데 날씨도 좋구 즐거웠어요??,NaN,NaN,netizen
47,허밍벨라,합정,서교동,루프탑? 이라고 할 수 있을 것 같음 일단 접근성이 좋고 두번째 방문인데 맛은 없음...,NaN,NaN,netizen
48,마가렛리버,합정,합정동,밀크티 머스캣향나고 넘 좋았어용 좌석도 편하고 테라스 캠핑느낌으로 되어있어서 아주 ...,NaN,NaN,netizen
49,마가렛리버,합정,합정동,카페가 아기자기해요ㅋㅋ,NaN,NaN,netizen
50,마가렛리버,합정,합정동,스콘맛집이어요??,NaN,NaN,netizen
51,트래블메이커,합정,동교동,아메리칸식 브런치로 딱 좋은 곳!! 간단히 한 끼 먹기 좋습니다~^^ 평범한 블랙퍼...,NaN,NaN,netizen
52,트래블메이커,합정,동교동,브런치가 맛있어 보여서 찾아갔는데 가성비도 좋고 매장 자체부터 미국 느낌 낭낭해요~,NaN,NaN,netizen
53,트래블메이커,합정,동교동,아침에 여유롭게 먹다가융????,NaN,NaN,netizen
54,NaN,NaN,NaN,NaN,NaN,NaN,netizen

In [3]:
import re

re.compile('[^가-힣]')을 사용할 때 string으로 변환해줘야합니다.

In [4]:
def extract_word(text):
    hangul = re.compile('[^가-힣]') 
    result = hangul.sub(' ', text) 
    return result

In [5]:
extract_word(df['evaluation'][19])
### 띄어쓰기 고쳐야할 것 같다.

'플라워카페 너무 이뻐요 들어갈때 꽃향기도 좋고  층도 있고 테라스도 있고 바나나주스 진짜 맛있었어요 딸기 케이크는 조금 더 달았으면 좋겠어요 굿굿'

In [6]:
df['evaluation'] = df['evaluation'].apply(lambda x : extract_word(str(x)))

In [7]:
df

,cafe_name,quary,region,evaluation,rating,coffee_price,who
0,umoae,합정,서교동,인테리어가 감각적이라고 느꼈습니다 사장님이 친절하시고 디저트가 맛있어요 소르베도 재...,NaN,NaN,netizen
1,umoae,합정,서교동,커피와 디저트 모두 너무 맛있어요 가게 분위기도 원목 가구를 써서 그런지 단정하고 ...,NaN,NaN,netizen
2,umoae,합정,서교동,프렌치토스트 소문대로 존맛탱,NaN,NaN,netizen
3,어반플랜트 합정,합정,합정동,자연에 둘러쌓여 있는듯한 색다른 기분도 느낄수있었고 시그니처 오믈렛 정말 맛있었어...,NaN,NaN,netizen
4,어반플랜트 합정,합정,합정동,직원분이 테이블링을 도와주셔서 웨이팅을 하다보면 이름을 불러주세요 음료도 맛있었고...,NaN,NaN,netizen
5,어반플랜트 합정,합정,합정동,카페 인테리어도 예쁘고 이름에 걸맞게 식물들이 많아서 좋았습니다 특히 건물 외부에...,NaN,NaN,netizen
6,포비 베이직,합정,합정동,이제 서울에 꽤나 많은 포비 매장이 생겼지만 역시나 최고는 포비 베이직 합정 매장입...,NaN,NaN,netizen
7,포비 베이직,합정,합정동,요기 빛도 너무 좋구 인테리어도 이쁘구 참새도 있음 참새 너무 익숙하게 빵 얻...,NaN,NaN,netizen
8,포비 베이직,합정,합정동,주말이나 저녁에 가보다가 평일 낮에 방문하니 너무 좋더라구요 그것도 봄 여유 ...,NaN,NaN,netizen
9,어썸마운틴,합정,동교동,에서 등반 후 먹는 흑임자치즈케이크와 아아 입니다 아이스아메리카노가 산미 없...,NaN,NaN,netizen
10,어썸마운틴,합정,동교동,카페가 이쁘고 감각적입니다 말차파운드는 못먹었지만 얼그레이도 맛있었어요 토마토바...,NaN,NaN,netizen
11,어썸마운틴,합정,동교동,맨날 강아지랑 산책할때마다 지나가는데 사람이 엄청 많습니다 처음에 생겼을때는 사람이...,NaN,NaN,netizen
12,943 킹스크로스CAFE,합정,서교동,해리포터 매니아라면 너무나 좋아할 카페입니다 음료도 비싸지만 맛있고 구경하기 재밌어요,NaN,NaN,netizen
13,944 킹스크로스CAFE,합정,서교동,해리포터를 좋아하는 사람과 함께하면 더 좋은 곳 해리포터 음악이 계속 나와서 좋...,NaN,NaN,netizen
14,945 킹스크로스CAFE,합정,서교동,홍대에서 어떤 카페를 갈까 친구들과 고민을 하던 중 해리포터 카페로 유명해서 선택하...,NaN,NaN,netizen
15,샌드커피 논탄토 연남,합정,동교동,카이막이 먹고 싶어서 찾아갔는데 저녁에 갔더니 품절이더라구요 아쉽긴 했지만 ...,NaN,NaN,netizen
16,샌드커피 논탄토 연남,합정,동교동,죤맛 너무 잘 먹었어요 토스트는 더 구워 달라고 할 걸 그랬어요 더 바삭한게 좋아...,NaN,NaN,netizen
17,샌드커피 논탄토 연남,합정,동교동,시원하고 쾌적하고 메뉴 신기 핸드드립 커피 과테말라 좋아요 다음엔 터키식 카이막도 ...,NaN,NaN,netizen
18,콜린,합정,서교동,갑자기 걷는데 비가내려서 들어왔어요 빗소리 들으면서 맥주 한잔 마시고 있는데 넘나...,NaN,NaN,netizen
19,콜린,합정,서교동,플라워카페 너무 이뻐요 들어갈때 꽃향기도 좋고 층도 있고 테라스도 있고 바나나주스...,NaN,NaN,netizen
20,콜린,합정,서교동,인절미 크루아상 대존맛탱구리구리 향기나는 꽃들에 둘러쌓여 디저트 먹으면서 기분전...,NaN,NaN,netizen
21,차곡파티세리,합정,서교동,에스프레소 맛집 원두 기름이 잘 어우러지는 신선한 원두로 갓내린 커피 초콜릿은 더 ...,NaN,NaN,netizen
22,차곡파티세리,합정,서교동,케이크가 정말 너무 맛있어요 녹차쉬폰인데 녹차 크림이 정말 진하고 맛있더라구요...,NaN,NaN,netizen
23,차곡파티세리,합정,서교동,음료도 맛있구 케이크가 넘 귀여워요 셀카찍기 좋은 예쁜 곳,NaN,NaN,netizen
24,브런치가,합정,동교동,크로크햄 치즈와 치킨퀘사디아를 주문했습니다 치킨 브리또를 먹으려고 했지만 품절이라...,NaN,NaN,netizen
25,브런치가,합정,동교동,음식도 맛있고 무엇보다 일찍 열어서 저희처럼 일찍 만나는 사람에게 딱이였어요,NaN,NaN,netizen
26,브런치가,합정,동교동,야외 테이블 자리마다 싱그러운 분위기 바람 시원하고 좋아요 직원 분들 친절하시고 ...,NaN,NaN,netizen
27,랑데자뷰 홍대점,합정,서교동,매장도 넓고 음료도 맛있어요 색감이 되게 이뻐 요 특히 한라봉에이드 찐 추천...,NaN,NaN,netizen
28,랑데자뷰 홍대점,합정,서교동,커피도 맛있고 분위기도 좋아요 사진찍을 곳도 많고 직원분들이 친절해용,NaN,NaN,netizen
29,랑데자뷰 홍대점,합정,서교동,훌륭훌륭 날이 더워서 에이드 주문했는데 넘 맛있구 직원들도 친절해요,NaN,NaN,netizen
30,1984,합정,동교동,갈 때마다 만석인 출판사 카페 볼거리도 많고 답답하지 않은 분위기라 편해요,NaN,NaN,netizen
31,1984,합정,동교동,분위기도 힙하고 샌드위치가 맛있네요 레몬에이드는 양 많고 레몬이 가득이라 좋았어요,NaN,NaN,netizen
32,1984,합정,동교동,다양한 메뉴가 있고 또 책이나 옷 신발 굿즈까지 있 어서 너무 신기해요 샌드위치 너...,NaN,NaN,netizen
33,얀 쿠브레,합정,동교동,요기 첨왔는데 왜 사람이 많은지 알겠네요 진짜 디저트도 딴곳에서 볼수없는 메뉴들이랑...,NaN,NaN,netizen
34,얀 쿠브레,합정,동교동,느끼하지도 않고 너무 달지도 않은 디저트 맛집입니다 포장이 예뻐서 선물하기도 좋습니다,NaN,NaN,netizen
35,얀 쿠브레,합정,동교동,디져트 가격에 놀래서 저렴이 들로만 구매 했어요 커피는 아이스라떼로 사람 ...,NaN,NaN,netizen
36,앤트러사이트 합정점,합정,합정동,매장이 완전 분위기 있어요 층은 대화하기 좋고 층은 공부하기 좋은 분위기네요...,NaN,NaN,netizen
37,앤트러사이트 합정점,합정,합정동,힙한 음악 여기 음악 개쩜 음악 일가견 있다면 여기 음악들 힙하다는걸 듣자마...,NaN,NaN,netizen
38,앤트러사이트 합정점,합정,합정동,드립커피 마시러 간혹 다니는 카페에요 저녁 시 정도에 가서 이미 드립은 마감이라...,NaN,NaN,netizen
39,빈브라더스 합정,합정,합정동,커피도 다 맛있고 디저트도 정말 맛있어요 특히 스콘이 심플하면서도 겉은 바삭하고 ...,NaN,NaN,netizen
40,빈브라더스 합정,합정,합정동,커피 맛있어요 전문가의 맛이죠 원래 유명한 곳이었구요 빵도 맛있구요 다만 ...,NaN,NaN,netizen
41,빈브라더스 합정,합정,합정동,옥션 테이스팅 코스 커피를 내려마신지 얼마 안돼서 이런 비싼 커피를 마셔도 맛을 ...,NaN,NaN,netizen
42,리피 메세나폴리스점,합정,서교동,합정역 브런치맛집 깔끔한인테리어 모임장소로 추 천 주차지원가능 잠봉뵈르 맛있음 ...,NaN,NaN,netizen
43,리피 메세나폴리스점,합정,서교동,인테리어도 이쁘고 브런치도 기대이상이었어요 넘 이쁘게 나와서 기분좋고 올타임 클...,NaN,NaN,netizen
44,리피 메세나폴리스점,합정,서교동,음식 따뜻하게 잘나왔구 다 맛있었어용 후무스샐러드처음먹는데 굳굳이네욤 저...,NaN,NaN,netizen
45,허밍벨라,합정,서교동,야외석부터 층여유롭고 배가불러 디저트맛집 디저트못먹규가용 망코 요건 ...,NaN,NaN,netizen
46,허밍벨라,합정,서교동,디저트 맛있어요 외부 테이블에서 마셨는데 날씨도 좋구 즐거웠어요,NaN,NaN,netizen
47,허밍벨라,합정,서교동,루프탑 이라고 할 수 있을 것 같음 일단 접근성이 좋고 두번째 방문인데 맛은 없음...,NaN,NaN,netizen
48,마가렛리버,합정,합정동,밀크티 머스캣향나고 넘 좋았어용 좌석도 편하고 테라스 캠핑느낌으로 되어있어서 아주 ...,NaN,NaN,netizen
49,마가렛리버,합정,합정동,카페가 아기자기해요,NaN,NaN,netizen
50,마가렛리버,합정,합정동,스콘맛집이어요,NaN,NaN,netizen
51,트래블메이커,합정,동교동,아메리칸식 브런치로 딱 좋은 곳 간단히 한 끼 먹기 좋습니다 평범한 블랙퍼...,NaN,NaN,netizen
52,트래블메이커,합정,동교동,브런치가 맛있어 보여서 찾아갔는데 가성비도 좋고 매장 자체부터 미국 느낌 낭낭해요,NaN,NaN,netizen
53,트래블메이커,합정,동교동,아침에 여유롭게 먹다가융,NaN,NaN,netizen
54,NaN,NaN,NaN,,NaN,NaN,netizen

In [8]:
!pip install konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
     |████████████████████████████████| 19.4 MB 1.4 MB/s
Collecting JPype1>=0.7.0
  Downloading JPype1-1.4.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (453 kB)
     |████████████████████████████████| 453 kB 33.7 MB/s
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.7/dist-packages (from konlpy) (4.2.6)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.7/dist-packages (from konlpy) (1.21.6)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from JPype1>=0.7.0->konlpy) (4.1.1)
Installing collected packages: JPype1, konlpy
Successfully installed JPype1-1.4.0 konlpy-0.6.0

In [9]:
from konlpy.tag import Okt
from konlpy.tag import Mecab
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
okt = Okt()

In [11]:
vectorizer = TfidfVectorizer(min_df = 3, ngram_range = (1,2), tokenizer = okt.phrases)

In [12]:
features = vectorizer.fit_transform(df['evaluation'])
pd.DataFrame(features.todense(), columns = vectorizer.get_feature_names_out())

,가성,기분,느낌,다음,대화,디저트,맛집,매장,메뉴,방문,...,친구들,카이,카페,커피,케이크,크림,테라스,테이블,평일,해리포터
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.678746,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.623869,0.466783,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.397271,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.524641,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.484926,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.410354,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.484926,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.432379,0.460625,...,0.000000,0.000000,0.332578,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.477705,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.384135,...,0.000000,0.000000,0.000000,0.244612,0.000000,0.310967,0.000000,0.000000,0.384135,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.388616,0.000000,0.280587,0.000000,0.000000,0.000000,0.000000,0.000000,0.388616,0.000000
10,0.000000,0.000000,0.423253,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.305595,0.269522,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.323210,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.275079,0.000000,0.000000,0.000000,0.000000,0.431980,0.000000
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.465823,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.645171
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
14,0.000000,0.348628,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.371402,0.000000,0.268158,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.371402
15,0.000000,0.000000,0.000000,0.379956,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.379956,0.274334,0.241951,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.523042,0.000000,0.000000,0.000000,0.423416,0.000000,0.000000,0.000000,0.000000
17,0.000000,0.000000,0.000000,0.551601,0.000000,0.000000,0.000000,0.000000,0.517778,0.000000,...,0.000000,0.551601,0.000000,0.351252,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.353291,0.000000,0.489313,0.000000,0.489313,0.000000,0.000000,0.000000
20,0.000000,0.781980,0.000000,0.000000,0.000000,0.623303,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.653226,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.468124,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.498336,0.403416,0.000000,0.000000,0.000000,0.000000
23,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.729107,0.000000,0.000000,0.000000,0.000000,0.000000
24,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,0.403553,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.378808,0.000000,...,0.403553,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.403553,0.000000,0.000000
27,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.416213,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
28,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.463121,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.680637,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
32,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.684399,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
33,0.000000,0.000000,0.000000,0.000000,0.000000,0.528439,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
34,0.000000,0.000000,0.000000,0.000000,0.000000,0.644100,0.764941,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.582501,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
36,0.000000,0.000000,0.000000,0.000000,0.501545,0.000000,0.000000,0.424417,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.406013,0.000000,0.000000,0.000000,0.000000
37,0.000000,0.000000,0.000000,0.478283,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.304564,0.000000,0.387183,0.478283,0.000000,0.000000,0.000000
38,0.000000,0.000000,0.000000,0.000000,0.457684,0.000000,0.000000,0.387301,0.000000,0.000000,...,0.000000,0.000000,0.330455,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,0.000000,0.000000,0.000000,0.000000,0.000000,0.489460,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.416571,0.000000,0.529574,0.000000,0.000000,0.000000,0.000000
40,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
41,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
42,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.613144,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
43,0.000000,0.634043,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
44,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
45,0.000000,0.000000,0.000000,0.000000,0.000000,0.488140,0.579721,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
46,0.000000,0.000000,0.000000,0.000000,0.000000,0.599081,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.800689,0.000000,0.000000
47,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.657857,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.532552,0.000000,0.000000,0.000000,0.000000
48,0.000000,0.000000,0.707107,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.707107,0.000000,0.000000,0.000000
49,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
51,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
52,0.544620,0.000000,0.544620,0.000000,0.000000,0.000000,0.000000,0.460868,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
53,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
54,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

In [14]:
cos_sim = cosine_similarity(features, features, dense_output=True)

In [15]:
pd.DataFrame(cos_sim)

,0,1,2,3,4,5,6,7,8,9,...,45,46,47,48,49,50,51,52,53,54
0,1.000000,0.316827,0.0,0.000000,0.000000,0.273838,0.000000,0.445978,0.000000,0.000000,...,0.331323,0.406624,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
1,0.316827,1.000000,0.0,0.210600,0.000000,0.000000,0.000000,0.189779,0.097177,0.000000,...,0.227856,0.279641,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
2,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
3,0.000000,0.210600,0.0,1.000000,0.000000,0.000000,0.000000,0.300246,0.153743,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
4,0.000000,0.000000,0.0,0.000000,1.000000,0.146381,0.410354,0.000000,0.000000,0.000000,...,0.000000,0.388275,0.000000,0.000000,0.000000,0.000000,0.392560,0.626293,0.0,0.0
5,0.273838,0.000000,0.0,0.000000,0.146381,1.000000,0.000000,0.226451,0.176942,0.093317,...,0.000000,0.000000,0.303025,0.000000,0.332578,0.000000,0.372887,0.164400,0.0,0.0
6,0.000000,0.000000,0.0,0.000000,0.410354,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.460868,0.0,0.0
7,0.445978,0.189779,0.0,0.300246,0.000000,0.226451,0.000000,1.000000,0.323208,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
8,0.000000,0.097177,0.0,0.153743,0.000000,0.176942,0.000000,0.323208,1.000000,0.298562,...,0.250615,0.000000,0.418312,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
9,0.000000,0.000000,0.0,0.000000,0.000000,0.093317,0.000000,0.000000,0.298562,1.000000,...,0.000000,0.000000,0.167538,0.000000,0.280587,0.000000,0.000000,0.000000,0.0,0.0
10,0.000000,0.107073,0.0,0.000000,0.000000,0.101634,0.000000,0.128752,0.065928,0.358019,...,0.000000,0.000000,0.000000,0.299285,0.305595,0.000000,0.000000,0.230512,0.0,0.0
11,0.219378,0.422921,0.0,0.145824,0.000000,0.000000,0.000000,0.131407,0.233226,0.300423,...,0.157772,0.193629,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
12,0.000000,0.000000,0.0,0.000000,0.275668,0.154923,0.000000,0.000000,0.000000,0.130704,...,0.000000,0.000000,0.000000,0.000000,0.465823,0.000000,0.000000,0.000000,0.0,0.0
13,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
14,0.220796,0.000000,0.0,0.182905,0.000000,0.372373,0.000000,0.182588,0.000000,0.408746,...,0.000000,0.000000,0.160117,0.000000,0.268158,0.000000,0.000000,0.000000,0.0,0.0
15,0.000000,0.096120,0.0,0.000000,0.000000,0.091238,0.000000,0.115581,0.205139,0.076975,...,0.000000,0.000000,0.000000,0.000000,0.274334,0.000000,0.000000,0.000000,0.0,0.0
16,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.131668,0.203262,...,0.000000,0.000000,0.225491,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
17,0.000000,0.139542,0.0,0.000000,0.000000,0.223876,0.000000,0.167795,0.085920,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
18,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
19,0.000000,0.000000,0.0,0.000000,0.000000,0.342886,0.000000,0.000000,0.000000,0.223743,...,0.000000,0.000000,0.000000,0.345996,0.353291,0.000000,0.000000,0.000000,0.0,0.0
20,0.423065,0.290947,0.0,0.410259,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.304259,0.373409,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
21,0.000000,0.185972,0.0,0.000000,0.000000,0.000000,0.000000,0.223625,0.114509,0.187218,...,0.378689,0.000000,0.316927,0.000000,0.000000,0.653226,0.000000,0.000000,0.0,0.0
22,0.000000,0.000000,0.0,0.199450,0.000000,0.000000,0.000000,0.267704,0.262529,0.126912,...,0.000000,0.000000,0.214840,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
23,0.000000,0.000000,0.0,0.000000,0.311532,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
24,0.000000,0.000000,0.0,0.259900,0.000000,0.000000,0.000000,0.348842,0.428074,0.417735,...,0.000000,0.000000,0.279955,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
25,0.000000,0.000000,0.0,0.334638,0.000000,0.000000,0.000000,0.000000,0.000000,0.183715,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
26,0.000000,0.152060,0.0,0.136228,0.519631,0.285606,0.000000,0.000000,0.155019,0.156827,...,0.263283,0.323120,0.000000,0.000000,0.000000,0.000000,0.326687,0.363814,0.0,0.0
27,0.000000,0.000000,0.0,0.000000,0.380952,0.000000,0.416213,0.000000,0.000000,0.125260,...,0.000000,0.000000,0.212044,0.000000,0.000000,0.000000,0.000000,0.191819,0.0,0.0
28,0.000000,0.458025,0.0,0.245508,0.000000,0.000000,0.000000,0.221235,0.113285,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
29,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
30,0.000000,0.355208,0.0,0.318225,0.000000,0.226365,0.000000,0.000000,0.000000,0.190978,...,0.000000,0.000000,0.000000,0.000000,0.680637,0.000000,0.000000,0.000000,0.0,0.0
31,0.000000,0.484846,0.0,0.434365,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
32,0.000000,0.000000,0.0,0.000000,0.000000,0.295920,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
33,0.358676,0.246666,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.396582,...,0.257952,0.316578,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
34,0.437181,0.300655,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.757863,0.385868,0.000000,0.000000,0.000000,0.764941,0.000000,0.000000,0.0,0.0
35,0.000000,0.231411,0.0,0.000000,0.000000,0.000000,0.000000,0.278264,0.142487,0.280683,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
36,0.000000,0.501882,0.0,0.169307,0.174161,0.000000,0.424417,0.000000,0.126257,0.000000,...,0.000000,0.000000,0.216223,0.000000,0.000000,0.000000,0.000000,0.195600,0.0,0.0
37,0.284336,0.120995,0.0,0.000000,0.000000,0.144375,0.000000,0.380625,0.194901,0.121805,...,0.000000,0.000000,0.206195,0.338197,0.000000,0.000000,0.000000,0.000000,0.0,0.0
38,0.000000,0.285535,0.0,0.000000,0.158931,0.109902,0.387301,0.000000,0.175812,0.209281,...,0.000000,0.000000,0.197314,0.000000,0.330455,0.000000,0.000000,0.178495,0.0,0.0
39,0.332219,0.393964,0.0,0.261822,0.000000,0.000000,0.000000,0.550420,0.446526,0.000000,...,0.238925,0.293226,0.282026,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
40,0.000000,0.397271,0.0,0.000000,0.000000,0.000000,0.000000,0.477705,0.244612,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
41,0.000000,0.397271,0.0,0.000000,0.000000,0.000000,0.000000,0.477705,0.244612,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
42,0.410216,0.000000,0.0,0.000000,0.219282,0.416585,0.000000,0.339229,0.000000,0.000000,...,0.355452,0.000000,0.000000,0.000000,0.000000,0.613144,0.558594,0.246275,0.0,0.0
43,0.401558,0.000000,0.0,0.332645,0.214653,0.407792,0.000000,0.332069,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.546804,0.241077,0.0,0.0
44,0.000000,0.000000,0.0,0.395211,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
45,0.331323,0.227856,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.250615,0.000000,...,1.000000,0.292435,0.000000,0.000000,0.000000,0.579721,0.000000,0.000000,0.0,0.0
46,0.406624,0.279641,0.0,0.000000,0.388275,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.292435,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
47,0.000000,0.000000,0.0,0.000000,0.000000,0.303025,0.000000,0.000000,0.418312,0.167538,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
48,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.385105,0.0,0.0
49,0.000000,0.000000,0.0,0.000000,0.000000,0.332578,0.000000,0.000000,0.000000,0.280587,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.0
50,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.579721,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,0.0
51,0.000000,0.000000,0.0,0.000000,0.392560,0.372887,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.440884,0.0,0.0
52,0.000000,0.000000,0.0,0.000000,0.626293,0.164400,0.460868,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.385105,0.000000,0.000000,0.440884,1.000000,0.0,0.0
53,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
54,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0

In [16]:
index = pd.DataFrame(cos_sim)[5].sort_values(ascending = False)[:11].index

In [17]:
df['evaluation'].iloc[index]

5     카페 인테리어도 예쁘고 이름에 걸맞게 식물들이 많아서 좋았습니다  특히 건물 외부에...
42    합정역 브런치맛집  깔끔한인테리어  모임장소로 추 천 주차지원가능 잠봉뵈르 맛있음 ...
43    인테리어도 이쁘고 브런치도 기대이상이었어요  넘 이쁘게 나와서 기분좋고  올타임 클...
51    아메리칸식 브런치로 딱 좋은 곳   간단히 한 끼 먹기 좋습니다    평범한 블랙퍼...
14    홍대에서 어떤 카페를 갈까 친구들과 고민을 하던 중 해리포터 카페로 유명해서 선택하...
19    플라워카페 너무 이뻐요 들어갈때 꽃향기도 좋고  층도 있고 테라스도 있고 바나나주스...
49                                         카페가 아기자기해요
47    루프탑  이라고 할 수 있을 것 같음 일단 접근성이 좋고 두번째 방문인데 맛은 없음...
32    다양한 메뉴가 있고 또 책이나 옷 신발 굿즈까지 있 어서 너무 신기해요 샌드위치 너...
26    야외 테이블 자리마다 싱그러운 분위기  바람 시원하고 좋아요 직원 분들 친절하시고 ...
0     인테리어가 감각적이라고 느꼈습니다 사장님이 친절하시고 디저트가 맛있어요 소르베도 재...
Name: evaluation, dtype: object

In [ ]:
# 리뷰와 가게명으로 딕셔너리 만들기
# cafe_to_eval = dict(zip(df['cafe_name'], df['evaluation']))
# eval_to_cafe = dict(zip(df['evaluation'], df['cafe_name']))

In [ ]:
'''
user_dict = {}

def my_want_cafe(location, ):
    global user_dict
    user_dict[movie] = rating

    return user_dict

def searching_movie(movie):
    movie_df = pd.DataFrame(list(set(zip(df['Title']))), columns = ['Title'])
    movie_df = movie_df[movie_df['Title'].map(lambda x : movie in x)]

    return movie_df
'''